function summary = plot_weddell_sea_trophic_topology()
%PLOT_WEDDELL_SEA_TROPHIC_TOPOLOGY Show the source-free Weddell Sea cycle.

    stats_dir = fileparts(mfilename('fullpath'));
    repo_root = fileparts(fileparts(stats_dir));
    input_file = fullfile(repo_root, 'src', 'matlab', 'data', ...
        'foodwebs_mat', 'Weddell Sea_tax_mass.mat');
    output_dir = fullfile(stats_dir, 'figures');
    if ~isfolder(output_dir)
        mkdir(output_dir);
    end

    input = load(input_file, 'net', 'taxonomy');
    net = spones(sparse(input.net));
    net = net - spdiags(diag(net), 0, size(net, 1), size(net, 1));
    taxonomy = strtrim(string(input.taxonomy(:)));

    undirected = spones(net | net');
    components = conncomp(graph(undirected));
    component_sizes = accumarray(components(:), 1);
    [~, largest_component] = max(component_sizes);
    largest_indices = find(components(:) == largest_component);

    largest_net = net(largest_indices, largest_indices);
    largest_taxonomy = taxonomy(largest_indices);
    prey_count = full(sum(largest_net, 1))';
    consumer_count = full(sum(largest_net, 2));
    basal = prey_count == 0;

    foodweb = digraph(largest_net);
    distances_from_basal = distances(foodweb, find(basal), 1:numnodes(foodweb));
    reachable = any(isfinite(distances_from_basal), 1)';
    unreachable_indices = find(~reachable);

    summary = table( ...
        largest_taxonomy, basal, reachable, prey_count, consumer_count, ...
        'VariableNames', { ...
            'Species', 'IsBasal', 'ReachableFromBasal', 'NumResources', ...
            'NumConsumers'});
    writetable(summary, fullfile(output_dir, ...
        'weddell_sea_trophic_reachability.csv'));
    writetable(summary(~reachable, :), fullfile(output_dir, ...
        'weddell_sea_unreachable_nodes.csv'));

    figure_handle = figure( ...
        'Visible', 'off', ...
        'Color', 'white', ...
        'Position', [100, 100, 1800, 820]);
    layout_handle = tiledlayout(figure_handle, 1, 2, ...
        'TileSpacing', 'compact', 'Padding', 'compact');

    full_axis = nexttile(layout_handle, 1);
    full_plot = plot(full_axis, foodweb, ...
        'Layout', 'force', ...
        'NodeLabel', {}, ...
        'MarkerSize', 2.5, ...
        'NodeColor', [0.25, 0.43, 0.63], ...
        'EdgeColor', [0.84, 0.86, 0.88], ...
        'LineWidth', 0.15, ...
        'ArrowSize', 2);
    highlight(full_plot, find(basal), ...
        'NodeColor', [0.20, 0.58, 0.32], 'MarkerSize', 3.5);
    highlight(full_plot, unreachable_indices, ...
        'NodeColor', [0.78, 0.16, 0.16], 'MarkerSize', 8);
    full_plot.NodeLabel = repmat({''}, numnodes(foodweb), 1);
    title(full_axis, sprintf( ...
        'Full Weddell Sea food web (%d species, %d links)', ...
        numnodes(foodweb), numedges(foodweb)), ...
        'FontWeight', 'bold');
    subtitle(full_axis, sprintf( ...
        '%d basal-reachable; %d without a basal path', ...
        sum(reachable), sum(~reachable)));
    axis(full_axis, 'off');
    hold(full_axis, 'on');
    basal_legend = scatter(full_axis, NaN, NaN, 45, [0.20, 0.58, 0.32], 'filled');
    reachable_legend = scatter(full_axis, NaN, NaN, 30, [0.25, 0.43, 0.63], 'filled');
    unreachable_legend = scatter(full_axis, NaN, NaN, 70, [0.78, 0.16, 0.16], 'filled');
    legend(full_axis, ...
        [basal_legend, reachable_legend, unreachable_legend], ...
        {'Basal', 'Basal-reachable', 'No basal path'}, ...
        'Location', 'southoutside', 'Orientation', 'horizontal');

    detail_axis = nexttile(layout_handle, 2);
    unreachable_net = largest_net(unreachable_indices, unreachable_indices);
    unreachable_foodweb = digraph(unreachable_net, ...
        cellstr(largest_taxonomy(unreachable_indices)));
    detail_plot = plot(detail_axis, unreachable_foodweb, ...
        'XData', [-1, 0, 1], ...
        'YData', [1, 0, 1], ...
        'NodeColor', [0.78, 0.16, 0.16], ...
        'MarkerSize', 13, ...
        'NodeFontSize', 11, ...
        'EdgeColor', [0.28, 0.28, 0.28], ...
        'LineWidth', 1.8, ...
        'ArrowSize', 14);
    detail_plot.NodeLabel = cellstr(largest_taxonomy(unreachable_indices));
    title(detail_axis, 'Basal-unreachable subgraph', 'FontWeight', 'bold');
    subtitle(detail_axis, ...
        'The Amphidinium-Gyrodinium cycle has no energy path from a basal node');
    text(detail_axis, 0, 1.45, ...
        sprintf('No incoming path from any of the %d basal species', sum(basal)), ...
        'HorizontalAlignment', 'center', ...
        'FontWeight', 'bold', ...
        'Color', [0.55, 0.08, 0.08]);
    text(detail_axis, 0, -0.28, ...
        'Arrows point from resource to consumer', ...
        'HorizontalAlignment', 'center', ...
        'Color', [0.25, 0.25, 0.25]);
    axis(detail_axis, 'off');
    xlim(detail_axis, [-1.8, 1.8]);
    ylim(detail_axis, [-0.5, 1.7]);

    title(layout_handle, ...
        'Why prey-averaged trophic level is undefined for Weddell Sea', ...
        'FontSize', 17, 'FontWeight', 'bold');

    output_file = fullfile(output_dir, ...
        'weddell_sea_foodweb_and_unreachable_cycle.png');
    exportgraphics(figure_handle, output_file, 'Resolution', 220);
    close(figure_handle);

    fprintf('Wrote %s\n', output_file);
    fprintf('Basal=%d, reachable=%d, unreachable=%d\n', ...
        sum(basal), sum(reachable), sum(~reachable));
end
