function results = run_wlnm_dir_neg_kfold(data, K, ~, config)
%RUN_WLNM_DIR_NEG_KFOLD k-fold CV wrapper for WLNM_dir_neg.
% Train positives are all positives excluding the fold.
% Test positives are the fold.
%
% This version mirrors the same CSV log metric extraction used by
% run_wlnm_dir_neg, while keeping CV-specific bookkeeping fields.

    if ~isfield(config,'cvK'), config.cvK = 5; end
    if ~isfield(config,'cvSeed'), config.cvSeed = 12345; end
    if ~isfield(config,'cvStratifyBackbone'), config.cvStratifyBackbone = true; end
    if ~isfield(config,'cvSaveConfusion'), config.cvSaveConfusion = false; end
    if ~isfield(config,'numExperiments'), config.numExperiments = 1; end
    if ~isfield(config,'evaluate_on_all_unseen'), config.evaluate_on_all_unseen = false; end
    if ~isfield(config,'use_role_filter'), config.use_role_filter = true; end
    if ~isfield(config,'thresholdMode'), config.thresholdMode = 'fixed'; end
    if ~isfield(config,'fixedThreshold'), config.fixedThreshold = 0.5; end
    if ~isfield(config,'thresholdSweepEnabled'), config.thresholdSweepEnabled = false; end
    if ~isfield(config,'thresholdSweepRange'), config.thresholdSweepRange = 0.10:0.10:0.90; end
    if ~isfield(config,'negativeMassEligibilityEnabled')
        config.negativeMassEligibilityEnabled = get_config_bool(config, 'negativeMassPreferenceEnabled', false);
    end
    if ~isfield(config,'negativeMassEligibilityThreshold')
        config.negativeMassEligibilityThreshold = get_config_number(config, 'negativeMassPreferenceThreshold', 1.0);
    end
    if ~isfield(config,'computeEcologicalMetrics'), config.computeEcologicalMetrics = true; end
    if ~isfield(config,'artifactDir'), config.artifactDir = 'data/result/confusion_matrix_csv/'; end
    if ~isfield(config,'version'), config.version = 'WLNM_dir_neg_kfold'; end

    dataname      = data.dataname;
    net           = spones(sparse(data.net));
    n             = size(net, 1);
    net           = net - spdiags(diag(net), 0, n, n);
    net           = spones(net);
    taxonomy      = data.taxonomy;
    mass          = data.mass;
    role          = data.role;
    nodeSelection = config.nodeSelection;

    backbone_mask = [];
    if isfield(data,'backbone_mask') && ~isempty(data.backbone_mask)
        backbone_mask = data.backbone_mask;
    end

    % Build folds on positive edges
    stratify = config.cvStratifyBackbone && ~isempty(backbone_mask);
    folds = kfold_edges_dir(net, config.cvK, config.cvSeed, backbone_mask, stratify);

    k = folds.k;

    if k == 0
        results = repmat(make_cv_result_template(K, NaN, 0, 0, 0, 0, empty_split_stats(), config), 0, 1);
        return;
    end

    ratioTrain = (k - 1) / k; % for reporting only

    rows_per_experiment = get_threshold_result_row_count(config);
    R = k * config.numExperiments * rows_per_experiment;
    results = repmat(make_cv_result_template(K, ratioTrain, k, 0, 0, 0, empty_split_stats(), config), R, 1);
    row = 0;

    for f = 1:k
        idx = find(folds.fold_id == f);

        test  = sparse(folds.i(idx), folds.j(idx), 1, folds.n, folds.n);
        train = net - test;

        % Sanity check: disjoint + covers all positives
        if nnz(train & test) ~= 0
            error('[CV] Train/Test overlap detected in fold %d.', f);
        end
        if nnz(train + test) ~= nnz(net)
            error('[CV] Train+Test does not cover all positives in fold %d.', f);
        end

        st = cv_split_stats(net, train, test, backbone_mask);

        fold_results = repmat(make_cv_result_template(K, ratioTrain, k, f, 0, 0, st, config), ...
            config.numExperiments * rows_per_experiment, 1);
        fold_row = 0;

        start_exp = 1;
        if logical(config.useParallel)
            res_cells = cell(config.numExperiments, 1);

            if logical(config.cvSaveConfusion)
                res_cells{1} = run_one_cv_experiment( ...
                    1, f, k, K, ratioTrain, st, config, dataname, train, test, ...
                    taxonomy, mass, role, nodeSelection, backbone_mask, true);
                start_exp = 2;
            end

            parfor e = start_exp:config.numExperiments
                res_cells{e} = run_one_cv_experiment( ...
                    e, f, k, K, ratioTrain, st, config, dataname, train, test, ...
                    taxonomy, mass, role, nodeSelection, backbone_mask, false);
            end

            for e = 1:config.numExperiments
                block = res_cells{e};
                n_block = numel(block);
                fold_results(fold_row + (1:n_block)) = block;
                fold_row = fold_row + n_block;
            end
        else
            for e = start_exp:config.numExperiments
                do_export = logical(config.cvSaveConfusion) && (e == 1);
                block = run_one_cv_experiment( ...
                    e, f, k, K, ratioTrain, st, config, dataname, train, test, ...
                    taxonomy, mass, role, nodeSelection, backbone_mask, do_export);
                n_block = numel(block);
                fold_results(fold_row + (1:n_block)) = block;
                fold_row = fold_row + n_block;
            end
        end

        results(row + (1:fold_row)) = fold_results(1:fold_row);
        row = row + fold_row;
    end

    results = results(1:row);
end

function rows = run_one_cv_experiment(e, f, k, K, ratioTrain, st, config, dataname, train, test, ...
        taxonomy, mass, role, nodeSelection, backbone_mask, do_export)

    seed = config.cvSeed + 1000*f + e;
    rng(seed, 'twister');

    t0 = tic;
    cv_tag = sprintf('cv_k%d_fold%02d_exp%02d', k, f, e);
    artifact_tag = sprintf('%s_seed%d', lower(char(string(config.version))), seed);
    encode_parallel = get_config_bool(config, 'useGraphEncodingParallel', false) && ~logical(config.useParallel);
    compute_ecological_metrics = get_config_bool(config, 'computeEcologicalMetrics', true);

    % WLNM_dir_neg owns uniform role-OR-mass eligibility sampling and controlled top-up.
    [roc_auc, pr_auc, thresholds, precisions, recalls, f1_scores, aux_rows] = WLNM_dir_neg( ...
        dataname, train, test, K, taxonomy, mass, role, nodeSelection, ratioTrain, ...
        'cv_tag', cv_tag, ...
        'save_confusion', do_export, ...
        'backbone_mask', backbone_mask, ...
        'export_backbone', false, ...
        'evaluate_on_all_unseen', config.evaluate_on_all_unseen, ...
        'use_role_filter', get_config_bool(config, 'use_role_filter', true), ...
        'artifact_tag', artifact_tag, ...
        'artifact_dir', config.artifactDir, ...
        'threshold_mode', config.thresholdMode, ...
        'fixed_threshold', config.fixedThreshold, ...
        'encode_parallel', encode_parallel, ...
        'compute_ecological_metrics', compute_ecological_metrics, ...
        'threshold_sweep_enabled', get_config_bool(config, 'thresholdSweepEnabled', false), ...
        'threshold_sweep_range', get_config_number(config, 'thresholdSweepRange', 0.10:0.10:0.90), ...
        'negative_mass_eligibility_enabled', get_config_bool(config, 'negativeMassEligibilityEnabled', false), ...
        'negative_mass_eligibility_threshold', get_config_number(config, 'negativeMassEligibilityThreshold', 1.0));

    elapsed_seconds = toc(t0);
    template = make_cv_result_template(K, ratioTrain, k, f, e, seed, st, config);
    rows = repmat(template, numel(thresholds), 1);
    for t = 1:numel(thresholds)
        rows(t) = populate_result_row( ...
            template, roc_auc, pr_auc, thresholds(t), precisions(t), ...
            recalls(t), f1_scores(t), elapsed_seconds, aux_rows(t));
    end

    fprintf('[CV] %s | K=%d | fold %d/%d | exp %d/%d | thresholds=%d | ROC-AUC=%.4f | PR-AUC=%.4f\n', ...
        dataname, K, f, k, e, config.numExperiments, numel(thresholds), roc_auc, pr_auc);
end

% ============================================================
% CV result row template
% Mirrors run_wlnm_dir_neg + CV bookkeeping fields
% ============================================================
function out = make_cv_result_template(K, ratioTrain, cvK, foldID, expID, seed, split_stats, config)
    if nargin < 8 || isempty(config)
        config = struct();
    end
    out = struct( ...
        'Version',get_config_text(config, 'version', 'WLNM_dir_neg_kfold'), ...
        'ROC_AUC',0, 'PR_AUC',0, 'TimeElapsed','', ...
        'K',K, 'TrainRatio',ratioTrain, 'BackboneRatio',0, ...
        'ExperimentID',expID, 'Seed',seed, ...
        'ThresholdMode',get_result_threshold_mode(config), ...
        'CvK',cvK, ...
        'FoldID',foldID, 'NumFolds',cvK, ...
        'Threshold',0, 'Precision',0, 'Recall',0, 'F1Score',0, ...
        'TestTP',NaN, ...
        'TestFP',NaN, ...
        'TestFN',NaN, ...
        'TestTN',NaN, ...
        'TestTPR',NaN, ...
        'TestTNR',NaN, ...
        'TestFPR',NaN, ...
        'TestFNR',NaN, ...
        'TestPrecision',NaN, ...
        'TestRecall',NaN, ...
        'TestF1Score',NaN, ...
        'TestAccuracy',NaN, ...
        'TestExpectedAccuracy',NaN, ...
        'TestKappa',NaN, ...
        'TestMCC',NaN, ...
        'TestTSS',NaN, ...
        'TotalLinks',split_stats.TotalLinks, ...
        'TrainLinks',split_stats.TrainLinks, ...
        'TestLinks',split_stats.TestLinks, ...
        'BackboneTotal',split_stats.BackboneTotal, ...
        'NonBackboneTotal',split_stats.NonBackboneTotal, ...
        'BackboneTrainLinks',split_stats.BackboneTrainLinks, ...
        'NonBackboneTrainLinks',split_stats.NonBackboneTrainLinks, ...
        'BackboneTestLinks',split_stats.BackboneTestLinks, ...
        'NonBackboneTestLinks',split_stats.NonBackboneTestLinks, ...
        'EmpiricalNumSpecies',NaN, ...
        'EmpiricalLinks',NaN, ...
        'EmpiricalConnectance',NaN, ...
        'EmpiricalMeanTrophicLevel',NaN, ...
        'EmpiricalMeanDegree',NaN, ...
        'EmpiricalMeanGenerality',NaN, ...
        'EmpiricalMeanVulnerability',NaN, ...
        'EmpiricalPropBasal',NaN, ...
        'EmpiricalPropIntermediate',NaN, ...
        'EmpiricalPropTop',NaN, ...
        'TrainNumSpecies',NaN, ...
        'TrainConnectance',NaN, ...
        'TrainMeanTrophicLevel',NaN, ...
        'TrainMeanDegree',NaN, ...
        'TrainMeanGenerality',NaN, ...
        'TrainMeanVulnerability',NaN, ...
        'TrainPropBasal',NaN, ...
        'TrainPropIntermediate',NaN, ...
        'TrainPropTop',NaN, ...
        'PseudoNumSpecies',NaN, ...
        'PseudoLinks',NaN, ...
        'PseudoConnectance',NaN, ...
        'PseudoMeanTrophicLevel',NaN, ...
        'PseudoMeanDegree',NaN, ...
        'PseudoMeanGenerality',NaN, ...
        'PseudoMeanVulnerability',NaN, ...
        'PseudoPropBasal',NaN, ...
        'PseudoPropIntermediate',NaN, ...
        'PseudoPropTop',NaN, ...
        'DeltaLinks',NaN, ...
        'DeltaConnectance',NaN, ...
        'DeltaMeanTrophicLevel',NaN, ...
        'DeltaMeanDegree',NaN, ...
        'DeltaMeanGenerality',NaN, ...
        'DeltaMeanVulnerability',NaN, ...
        'DeltaPropBasal',NaN, ...
        'DeltaPropIntermediate',NaN, ...
        'DeltaPropTop',NaN, ...
        'PseudoTP',NaN, ...
        'PseudoFP',NaN, ...
        'PseudoFN',NaN, ...
        'PseudoTN',NaN, ...
        'PseudoTPR',NaN, ...
        'PseudoTNR',NaN, ...
        'PseudoFPR',NaN, ...
        'PseudoFNR',NaN, ...
        'PseudoPrecision',NaN, ...
        'PseudoRecall',NaN, ...
        'PseudoF1Score',NaN, ...
        'PseudoMCC',NaN, ...
        'PseudoTSS',NaN, ...
        'PseudoJaccardLinks',NaN, ...
        'NumPredictedNovelLinks',NaN, ...
        'NumTrueNovelLinks',NaN, ...
        'EvaluateOnAllUnseen',NaN ...
    );

    out = add_extended_metric_defaults(out, 'Empirical');
    out = add_extended_metric_defaults(out, 'Train');
    out = add_extended_metric_defaults(out, 'Pseudo');
    out = add_extended_metric_defaults(out, 'Delta');
    out = add_networkx_trophic_diagnostic_defaults(out, 'Empirical');
    out = add_networkx_trophic_diagnostic_defaults(out, 'Train');
    out = add_networkx_trophic_diagnostic_defaults(out, 'Pseudo');
end

% ============================================================
% Empty split stats template
% ============================================================
function st = empty_split_stats()
    st = struct( ...
        'TotalLinks',0, ...
        'TrainLinks',0, ...
        'TestLinks',0, ...
        'BackboneTotal',0, ...
        'NonBackboneTotal',0, ...
        'BackboneTrainLinks',0, ...
        'NonBackboneTrainLinks',0, ...
        'BackboneTestLinks',0, ...
        'NonBackboneTestLinks',0 ...
    );
end

% ============================================================
% Fill predictive + ecological metrics into result row
% ============================================================
function out = populate_result_row(out, roc_auc, pr_auc, thr, prec, rec, f1, elapsed_seconds, aux)

    out.ROC_AUC     = roc_auc;
    out.PR_AUC      = pr_auc;
    out.TimeElapsed = datestr(seconds(elapsed_seconds), 'HH:MM:SS');
    out.Threshold   = thr;
    out.Precision   = prec;
    out.Recall      = rec;
    out.F1Score     = f1;

    flat = flatten_aux_metrics(aux);
    fn = fieldnames(flat);
    for k = 1:numel(fn)
        out.(fn{k}) = flat.(fn{k});
    end
end

% ============================================================
% Flatten aux struct from WLNM_dir_neg into scalar fields
% ============================================================
function flat = flatten_aux_metrics(aux)

    flat = struct( ...
        'EmpiricalNumSpecies',NaN, ...
        'EmpiricalLinks',NaN, ...
        'EmpiricalConnectance',NaN, ...
        'EmpiricalMeanTrophicLevel',NaN, ...
        'EmpiricalMeanDegree',NaN, ...
        'EmpiricalMeanGenerality',NaN, ...
        'EmpiricalMeanVulnerability',NaN, ...
        'EmpiricalPropBasal',NaN, ...
        'EmpiricalPropIntermediate',NaN, ...
        'EmpiricalPropTop',NaN, ...
        'TrainNumSpecies',NaN, ...
        'TrainConnectance',NaN, ...
        'TrainMeanTrophicLevel',NaN, ...
        'TrainMeanDegree',NaN, ...
        'TrainMeanGenerality',NaN, ...
        'TrainMeanVulnerability',NaN, ...
        'TrainPropBasal',NaN, ...
        'TrainPropIntermediate',NaN, ...
        'TrainPropTop',NaN, ...
        'PseudoNumSpecies',NaN, ...
        'PseudoLinks',NaN, ...
        'PseudoConnectance',NaN, ...
        'PseudoMeanTrophicLevel',NaN, ...
        'PseudoMeanDegree',NaN, ...
        'PseudoMeanGenerality',NaN, ...
        'PseudoMeanVulnerability',NaN, ...
        'PseudoPropBasal',NaN, ...
        'PseudoPropIntermediate',NaN, ...
        'PseudoPropTop',NaN, ...
        'DeltaLinks',NaN, ...
        'DeltaConnectance',NaN, ...
        'DeltaMeanTrophicLevel',NaN, ...
        'DeltaMeanDegree',NaN, ...
        'DeltaMeanGenerality',NaN, ...
        'DeltaMeanVulnerability',NaN, ...
        'DeltaPropBasal',NaN, ...
        'DeltaPropIntermediate',NaN, ...
        'DeltaPropTop',NaN, ...
        'TestTP',NaN, ...
        'TestFP',NaN, ...
        'TestFN',NaN, ...
        'TestTN',NaN, ...
        'TestTPR',NaN, ...
        'TestTNR',NaN, ...
        'TestFPR',NaN, ...
        'TestFNR',NaN, ...
        'TestPrecision',NaN, ...
        'TestRecall',NaN, ...
        'TestF1Score',NaN, ...
        'TestAccuracy',NaN, ...
        'TestExpectedAccuracy',NaN, ...
        'TestKappa',NaN, ...
        'TestMCC',NaN, ...
        'TestTSS',NaN, ...
        'PseudoTP',NaN, ...
        'PseudoFP',NaN, ...
        'PseudoFN',NaN, ...
        'PseudoTN',NaN, ...
        'PseudoTPR',NaN, ...
        'PseudoTNR',NaN, ...
        'PseudoFPR',NaN, ...
        'PseudoFNR',NaN, ...
        'PseudoPrecision',NaN, ...
        'PseudoRecall',NaN, ...
        'PseudoF1Score',NaN, ...
        'PseudoMCC',NaN, ...
        'PseudoTSS',NaN, ...
        'PseudoJaccardLinks',NaN, ...
        'NumPredictedNovelLinks',NaN, ...
        'NumTrueNovelLinks',NaN, ...
        'EvaluateOnAllUnseen',NaN ...
    );

    flat = add_extended_metric_defaults(flat, 'Empirical');
    flat = add_extended_metric_defaults(flat, 'Train');
    flat = add_extended_metric_defaults(flat, 'Pseudo');
    flat = add_extended_metric_defaults(flat, 'Delta');
    flat = add_networkx_trophic_diagnostic_defaults(flat, 'Empirical');
    flat = add_networkx_trophic_diagnostic_defaults(flat, 'Train');
    flat = add_networkx_trophic_diagnostic_defaults(flat, 'Pseudo');

    if nargin == 0 || isempty(aux)
        return;
    end

    % ---- empirical metrics ----
    if isfield(aux, 'empirical_metrics') && ~isempty(aux.empirical_metrics)
        m = aux.empirical_metrics;
        flat.EmpiricalNumSpecies        = safe_field(m, 'NumSpecies');
        flat.EmpiricalLinks             = safe_field(m, 'NumLinks');
        flat.EmpiricalConnectance       = safe_field(m, 'Connectance');
        flat.EmpiricalMeanTrophicLevel  = safe_field(m, 'MeanTrophicLevel');
        flat.EmpiricalMeanDegree        = safe_field(m, 'MeanDegree');
        flat.EmpiricalMeanGenerality    = safe_field(m, 'MeanGenerality');
        flat.EmpiricalMeanVulnerability = safe_field(m, 'MeanVulnerability');
        flat.EmpiricalPropBasal         = safe_field(m, 'PropBasal');
        flat.EmpiricalPropIntermediate  = safe_field(m, 'PropIntermediate');
        flat.EmpiricalPropTop           = safe_field(m, 'PropTop');
        flat = copy_extended_metrics(flat, m, 'Empirical');
        flat = copy_networkx_trophic_diagnostics(flat, m, 'Empirical');
    end

    % ---- train metrics ----
    if isfield(aux, 'train_metrics') && ~isempty(aux.train_metrics)
        m = aux.train_metrics;
        flat.TrainNumSpecies        = safe_field(m, 'NumSpecies');
        flat.TrainConnectance       = safe_field(m, 'Connectance');
        flat.TrainMeanTrophicLevel  = safe_field(m, 'MeanTrophicLevel');
        flat.TrainMeanDegree        = safe_field(m, 'MeanDegree');
        flat.TrainMeanGenerality    = safe_field(m, 'MeanGenerality');
        flat.TrainMeanVulnerability = safe_field(m, 'MeanVulnerability');
        flat.TrainPropBasal         = safe_field(m, 'PropBasal');
        flat.TrainPropIntermediate  = safe_field(m, 'PropIntermediate');
        flat.TrainPropTop           = safe_field(m, 'PropTop');
        flat = copy_extended_metrics(flat, m, 'Train');
        flat = copy_networkx_trophic_diagnostics(flat, m, 'Train');
    end

    % ---- pseudo metrics ----
    if isfield(aux, 'pseudo_metrics') && ~isempty(aux.pseudo_metrics)
        m = aux.pseudo_metrics;
        flat.PseudoNumSpecies        = safe_field(m, 'NumSpecies');
        flat.PseudoLinks             = safe_field(m, 'NumLinks');
        flat.PseudoConnectance       = safe_field(m, 'Connectance');
        flat.PseudoMeanTrophicLevel  = safe_field(m, 'MeanTrophicLevel');
        flat.PseudoMeanDegree        = safe_field(m, 'MeanDegree');
        flat.PseudoMeanGenerality    = safe_field(m, 'MeanGenerality');
        flat.PseudoMeanVulnerability = safe_field(m, 'MeanVulnerability');
        flat.PseudoPropBasal         = safe_field(m, 'PropBasal');
        flat.PseudoPropIntermediate  = safe_field(m, 'PropIntermediate');
        flat.PseudoPropTop           = safe_field(m, 'PropTop');
        flat = copy_extended_metrics(flat, m, 'Pseudo');
        flat = copy_networkx_trophic_diagnostics(flat, m, 'Pseudo');
    end

    % ---- deltas ----
    flat.DeltaLinks             = flat.PseudoLinks            - flat.EmpiricalLinks;
    flat.DeltaConnectance       = flat.PseudoConnectance      - flat.EmpiricalConnectance;
    flat.DeltaMeanTrophicLevel  = flat.PseudoMeanTrophicLevel - flat.EmpiricalMeanTrophicLevel;
    flat.DeltaMeanDegree        = flat.PseudoMeanDegree       - flat.EmpiricalMeanDegree;
    flat.DeltaMeanGenerality    = flat.PseudoMeanGenerality   - flat.EmpiricalMeanGenerality;
    flat.DeltaMeanVulnerability = flat.PseudoMeanVulnerability- flat.EmpiricalMeanVulnerability;
    flat.DeltaPropBasal         = flat.PseudoPropBasal        - flat.EmpiricalPropBasal;
    flat.DeltaPropIntermediate  = flat.PseudoPropIntermediate - flat.EmpiricalPropIntermediate;
    flat.DeltaPropTop           = flat.PseudoPropTop          - flat.EmpiricalPropTop;
    flat = compute_extended_metric_deltas(flat);

    % ---- test-set classification metrics ----
    if isfield(aux, 'test_metrics') && ~isempty(aux.test_metrics)
        t = aux.test_metrics;
        flat.TestTP               = safe_field(t, 'TP');
        flat.TestFP               = safe_field(t, 'FP');
        flat.TestFN               = safe_field(t, 'FN');
        flat.TestTN               = safe_field(t, 'TN');
        flat.TestTPR              = safe_field(t, 'TPR');
        flat.TestTNR              = safe_field(t, 'TNR');
        flat.TestFPR              = safe_field(t, 'FPR');
        flat.TestFNR              = safe_field(t, 'FNR');
        flat.TestPrecision        = safe_field(t, 'Precision');
        flat.TestRecall           = safe_field(t, 'Recall');
        flat.TestF1Score          = safe_field(t, 'F1Score');
        flat.TestAccuracy         = safe_field(t, 'Accuracy');
        flat.TestExpectedAccuracy = safe_field(t, 'ExpectedAccuracy');
        flat.TestKappa            = safe_field(t, 'Kappa');
        flat.TestMCC              = safe_field(t, 'MCC');
        flat.TestTSS              = safe_field(t, 'TSS');
    end

    % ---- comparison metrics ----
    if isfield(aux, 'comparison_metrics') && ~isempty(aux.comparison_metrics)
        c = aux.comparison_metrics;
        flat.PseudoTP           = safe_field(c, 'TP');
        flat.PseudoFP           = safe_field(c, 'FP');
        flat.PseudoFN           = safe_field(c, 'FN');
        flat.PseudoTN           = safe_field(c, 'TN');
        flat.PseudoTPR          = safe_field(c, 'TPR');
        flat.PseudoTNR          = safe_field(c, 'TNR');
        flat.PseudoFPR          = safe_field(c, 'FPR');
        flat.PseudoFNR          = safe_field(c, 'FNR');
        flat.PseudoPrecision    = safe_field(c, 'Precision');
        flat.PseudoRecall       = safe_field(c, 'Recall');
        flat.PseudoF1Score      = safe_field(c, 'F1Score');
        flat.PseudoMCC          = safe_field(c, 'MCC');
        flat.PseudoTSS          = safe_field(c, 'TSS');
        flat.PseudoJaccardLinks = safe_field(c, 'JaccardLinks');
    end

    % ---- bookkeeping ----
    if isfield(aux, 'NumPredictedNovelLinks')
        flat.NumPredictedNovelLinks = aux.NumPredictedNovelLinks;
    end
    if isfield(aux, 'NumTrueNovelLinks')
        flat.NumTrueNovelLinks = aux.NumTrueNovelLinks;
    end
    if isfield(aux, 'EvaluateOnAllUnseen')
        flat.EvaluateOnAllUnseen = double(aux.EvaluateOnAllUnseen);
    end
end

% ============================================================
% Safe struct field access
% ============================================================
function s = add_extended_metric_defaults(s, prefix)
    suffixes = extended_metric_suffixes();
    for i = 1:numel(suffixes)
        s.([prefix suffixes{i}]) = NaN;
    end
end

function s = add_networkx_trophic_diagnostic_defaults(s, prefix)
    suffixes = networkx_trophic_diagnostic_suffixes();
    for i = 1:numel(suffixes)
        s.([prefix suffixes{i}]) = NaN;
    end
end

function s = copy_extended_metrics(s, metrics, prefix)
    suffixes = extended_metric_suffixes();
    for i = 1:numel(suffixes)
        suffix = suffixes{i};
        s.([prefix suffix]) = safe_field(metrics, suffix);
    end
end

function s = copy_networkx_trophic_diagnostics(s, metrics, prefix)
    suffixes = networkx_trophic_diagnostic_suffixes();
    for i = 1:numel(suffixes)
        suffix = suffixes{i};
        s.([prefix suffix]) = safe_field(metrics, suffix);
    end
end

function s = compute_extended_metric_deltas(s)
    suffixes = extended_metric_suffixes();
    for i = 1:numel(suffixes)
        suffix = suffixes{i};
        s.(['Delta' suffix]) = s.(['Pseudo' suffix]) - s.(['Empirical' suffix]);
    end
end

function suffixes = extended_metric_suffixes()
    suffixes = { ...
        'DegreeStd', ...
        'DegreeCV', ...
        'DegreeGini', ...
        'GeneralityStd', ...
        'GeneralityCV', ...
        'GeneralityGini', ...
        'VulnerabilityStd', ...
        'VulnerabilityCV', ...
        'VulnerabilityGini', ...
        'TrophicLevelStd', ...
        'TrophicLevelCV', ...
        'TrophicLevelRange', ...
        'NetworkXMeanTrophicLevel', ...
        'NetworkXTrophicLevelStd', ...
        'NetworkXTrophicLevelRange', ...
        'MeanLocalClustering', ...
        'Transitivity', ...
        'NumTriangles', ...
        'TriangleDensity', ...
        'MeanDietOverlap' ...
    };
end

function suffixes = networkx_trophic_diagnostic_suffixes()
    suffixes = { ...
        'NetworkXTrophicLevelNumSpeciesFull', ...
        'NetworkXTrophicLevelNumSpeciesLargest', ...
        'NetworkXTrophicLevelNumSpeciesWithLevel', ...
        'NetworkXTrophicLevelLargestFraction', ...
        'NetworkXTrophicLevelStatusCode' ...
    };
end

function val = safe_field(s, f)
    if isstruct(s) && isfield(s, f) && ~isempty(s.(f))
        val = s.(f);
    else
        val = NaN;
    end
end

function value = get_config_text(config, field, default_value)
    if isfield(config, field) && ~isempty(config.(field))
        value = char(string(config.(field)));
    else
        value = char(string(default_value));
    end
end

function value = get_config_bool(config, field, default_value)
    if isfield(config, field) && ~isempty(config.(field))
        value = logical(config.(field));
    else
        value = logical(default_value);
    end
end

function value = get_config_number(config, field, default_value)
    if isfield(config, field) && ~isempty(config.(field))
        value = config.(field);
    else
        value = default_value;
    end
end

function n = get_threshold_result_row_count(config)
    if get_config_bool(config, 'thresholdSweepEnabled', false)
        thresholds = normalize_threshold_values( ...
            get_config_number(config, 'thresholdSweepRange', 0.10:0.10:0.90));
        n = numel(thresholds);
    else
        n = 1;
    end
end

function thresholds = normalize_threshold_values(values)
    thresholds = double(values(:)');
    thresholds = thresholds(isfinite(thresholds));
    thresholds = unique(thresholds);
    thresholds = thresholds(thresholds >= 0 & thresholds <= 1);

    if isempty(thresholds)
        error('[run_wlnm_dir_neg_kfold] thresholdSweepRange must contain at least one finite value in [0, 1].');
    end
end

function mode = get_result_threshold_mode(config)
    if get_config_bool(config, 'thresholdSweepEnabled', false)
        mode = 'threshold_sweep';
    else
        mode = get_config_text(config, 'thresholdMode', 'fixed');
    end
end
