function results = run_wlnm_original(data, K, ratioTrain, config)
    %RUN_WLNM_ORIGINAL Runner for WLNM with original sampling.

    % Preallocate result objects with extended CSV schema
    results = repmat(make_result_template_original(K, ratioTrain, empty_split_stats_original(), config, 0, 0), ...
        config.numExperiments, 1);

    % Broadcast-friendly locals
    dataname      = data.dataname;
    net           = data.net;
    taxonomy      = data.taxonomy;
    mass          = data.mass;
    role          = data.role;
    nodeSelection = config.nodeSelection;
    baseSeed      = get_config_number_original(config, 'baseSeed', 12345);
    resampleSplits = get_config_bool_original(config, 'resampleSplitsEachExperiment', true);
    saveAux = get_config_bool_original(config, 'exportAuxiliaryCSVs', false);
    artifactDir = get_config_text_original(config, 'artifactDir', 'data/result/confusion_matrix_csv/');
    thresholdMode = get_config_text_original(config, 'thresholdMode', 'fixed');
    fixedThreshold = get_config_number_original(config, 'fixedThreshold', 0.5);
    encodeParallel = get_config_bool_original(config, 'useGraphEncodingParallel', false) && ~logical(config.useParallel);
    computeEcologicalMetrics = get_config_bool_original(config, 'computeEcologicalMetrics', true);

    sharedTrain = [];
    sharedTest = [];
    sharedStats = [];
    if ~resampleSplits
        splitSeed = make_experiment_seed_original(baseSeed, dataname, K, ratioTrain, 0);
        rng(splitSeed, 'twister');
        [sharedTrain, sharedTest, ~, ~] = DivideNet_original( ...
            net, ratioTrain, string(nodeSelection), true, ...
            config.checkConnectivity, config.adaptiveConnectivity);
        sharedStats = make_split_stats_original(sharedTrain, sharedTest);
    end

    % Execute experiments
    if config.useParallel
        startIdx = 1;
        if saveAux
            results(1) = one_experiment_original( ...
                1, baseSeed, dataname, net, K, ratioTrain, taxonomy, mass, role, ...
                nodeSelection, config, sharedTrain, sharedTest, sharedStats, true, ...
                artifactDir, thresholdMode, fixedThreshold, encodeParallel, computeEcologicalMetrics);
            startIdx = 2;
        end

        if startIdx <= config.numExperiments
            parfor i = startIdx:config.numExperiments
                results(i) = one_experiment_original( ...
                    i, baseSeed, dataname, net, K, ratioTrain, taxonomy, mass, role, ...
                    nodeSelection, config, sharedTrain, sharedTest, sharedStats, false, ...
                    artifactDir, thresholdMode, fixedThreshold, encodeParallel, computeEcologicalMetrics);
            end
        end
    else
        for i = 1:config.numExperiments
            results(i) = one_experiment_original( ...
                i, baseSeed, dataname, net, K, ratioTrain, taxonomy, mass, role, ...
                nodeSelection, config, sharedTrain, sharedTest, sharedStats, saveAux && i == 1, ...
                artifactDir, thresholdMode, fixedThreshold, encodeParallel, computeEcologicalMetrics);
        end
    end
end

function r = one_experiment_original(i, baseSeed, dataname, net, K, ratioTrain, taxonomy, mass, role, ...
        nodeSelection, config, sharedTrain, sharedTest, sharedStats, saveConfusion, artifactDir, ...
        thresholdMode, fixedThreshold, encodeParallel, computeEcologicalMetrics)

    seed = make_experiment_seed_original(baseSeed, dataname, K, ratioTrain, i);
    rng(seed, 'twister');

    if isempty(sharedTrain)
        [train, test, ~, ~] = DivideNet_original( ...
            net, ratioTrain, string(nodeSelection), true, ...
            config.checkConnectivity, config.adaptiveConnectivity);
        splitStats = make_split_stats_original(train, test);
    else
        train = sharedTrain;
        test = sharedTest;
        splitStats = sharedStats;
    end

    t0 = tic;
    disp(['Experiment ', num2str(i), ' (node selection: ', char(nodeSelection), ') - Running WLNM_original...']);

    artifactTag = sprintf('%s_exp%03d_seed%d', lower(get_config_text_original(config, 'version', 'WLNM_original')), i, seed);

    [roc_auc, pr_auc, best_threshold, best_precision, best_recall, best_f1_score, aux] = ...
        WLNM_original(dataname, train, test, K, taxonomy, mass, role, nodeSelection, ratioTrain, ...
            'save_confusion', saveConfusion, ...
            'artifact_tag', artifactTag, ...
            'artifact_dir', artifactDir, ...
            'threshold_mode', thresholdMode, ...
            'fixed_threshold', fixedThreshold, ...
            'encode_parallel', encodeParallel, ...
            'compute_ecological_metrics', computeEcologicalMetrics);

    r = make_result_template_original(K, ratioTrain, splitStats, config, i, seed);
    r = populate_result_row_original( ...
        r, roc_auc, pr_auc, best_threshold, best_precision, best_recall, ...
        best_f1_score, toc(t0), aux);
end

% ============================================================
% Result row template (extended schema for CSV compatibility)
% ============================================================
function out = make_result_template_original(K, ratioTrain, splitStats, config, expID, seed)
    if nargin < 4 || isempty(config)
        config = struct();
    end
    if nargin < 5
        expID = 0;
    end
    if nargin < 6
        seed = 0;
    end

    out = struct( ...
        'Version', get_config_text_original(config, 'version', 'WLNM_original'), ...
        'ROC_AUC', 0, ...
        'PR_AUC', 0, ...
        'TimeElapsed', '', ...
        'K', K, ...
        'TrainRatio', ratioTrain, ...
        'ExperimentID', expID, ...
        'Seed', seed, ...
        'ThresholdMode', get_config_text_original(config, 'thresholdMode', 'fixed'), ...
        'CvK', 0, ...
        'FoldID', 0, ...
        'NumFolds', 0, ...
        'Threshold', 0, ...
        'Precision', 0, ...
        'Recall', 0, ...
        'F1Score', 0, ...
        'TotalLinks', splitStats.TotalLinks, ...
        'TrainLinks', splitStats.TrainLinks, ...
        'TestLinks', splitStats.TestLinks, ...
        'BackboneTotal', splitStats.BackboneTotal, ...
        'NonBackboneTotal', splitStats.NonBackboneTotal, ...
        'BackboneTrainLinks', splitStats.BackboneTrainLinks, ...
        'NonBackboneTrainLinks', splitStats.NonBackboneTrainLinks, ...
        'BackboneTestLinks', splitStats.BackboneTestLinks, ...
        'NonBackboneTestLinks', splitStats.NonBackboneTestLinks, ...
        'EmpiricalNumSpecies', NaN, ...
        'EmpiricalLinks', NaN, ...
        'EmpiricalConnectance', NaN, ...
        'EmpiricalMeanTrophicLevel', NaN, ...
        'EmpiricalMeanDegree', NaN, ...
        'EmpiricalMeanGenerality', NaN, ...
        'EmpiricalMeanVulnerability', NaN, ...
        'EmpiricalPropBasal', NaN, ...
        'EmpiricalPropIntermediate', NaN, ...
        'EmpiricalPropTop', NaN, ...
        'PseudoNumSpecies', NaN, ...
        'PseudoLinks', NaN, ...
        'PseudoConnectance', NaN, ...
        'PseudoMeanTrophicLevel', NaN, ...
        'PseudoMeanDegree', NaN, ...
        'PseudoMeanGenerality', NaN, ...
        'PseudoMeanVulnerability', NaN, ...
        'PseudoPropBasal', NaN, ...
        'PseudoPropIntermediate', NaN, ...
        'PseudoPropTop', NaN, ...
        'DeltaLinks', NaN, ...
        'DeltaConnectance', NaN, ...
        'DeltaMeanTrophicLevel', NaN, ...
        'DeltaMeanDegree', NaN, ...
        'DeltaMeanGenerality', NaN, ...
        'DeltaMeanVulnerability', NaN, ...
        'DeltaPropBasal', NaN, ...
        'DeltaPropIntermediate', NaN, ...
        'DeltaPropTop', NaN, ...
        'PseudoTP', NaN, ...
        'PseudoFP', NaN, ...
        'PseudoFN', NaN, ...
        'PseudoTN', NaN, ...
        'PseudoTPR', NaN, ...
        'PseudoTNR', NaN, ...
        'PseudoFPR', NaN, ...
        'PseudoFNR', NaN, ...
        'PseudoPrecision', NaN, ...
        'PseudoRecall', NaN, ...
        'PseudoF1Score', NaN, ...
        'PseudoTSS', NaN, ...
        'PseudoJaccardLinks', NaN, ...
        'NumPredictedNovelLinks', NaN, ...
        'NumTrueNovelLinks', NaN, ...
        'EvaluateOnAllUnseen', 0 ...
    );
end

% ============================================================
% Fill predictive + auxiliary metrics into result row
% ============================================================
function out = populate_result_row_original(out, roc_auc, pr_auc, thr, prec, rec, f1, elapsed_seconds, aux)
    out.ROC_AUC     = roc_auc;
    out.PR_AUC      = pr_auc;
    out.TimeElapsed = datestr(seconds(elapsed_seconds), 'HH:MM:SS');
    out.Threshold   = thr;
    out.Precision   = prec;
    out.Recall      = rec;
    out.F1Score     = f1;

    flat = flatten_aux_metrics_original(aux);
    fn = fieldnames(flat);
    for k = 1:numel(fn)
        out.(fn{k}) = flat.(fn{k});
    end
end

% ============================================================
% Flatten aux struct into scalar CSV fields
% ============================================================
function flat = flatten_aux_metrics_original(aux)

    flat = struct( ...
        'EmpiricalNumSpecies', NaN, ...
        'EmpiricalLinks', NaN, ...
        'EmpiricalConnectance', NaN, ...
        'EmpiricalMeanTrophicLevel', NaN, ...
        'EmpiricalMeanDegree', NaN, ...
        'EmpiricalMeanGenerality', NaN, ...
        'EmpiricalMeanVulnerability', NaN, ...
        'EmpiricalPropBasal', NaN, ...
        'EmpiricalPropIntermediate', NaN, ...
        'EmpiricalPropTop', NaN, ...
        'PseudoNumSpecies', NaN, ...
        'PseudoLinks', NaN, ...
        'PseudoConnectance', NaN, ...
        'PseudoMeanTrophicLevel', NaN, ...
        'PseudoMeanDegree', NaN, ...
        'PseudoMeanGenerality', NaN, ...
        'PseudoMeanVulnerability', NaN, ...
        'PseudoPropBasal', NaN, ...
        'PseudoPropIntermediate', NaN, ...
        'PseudoPropTop', NaN, ...
        'DeltaLinks', NaN, ...
        'DeltaConnectance', NaN, ...
        'DeltaMeanTrophicLevel', NaN, ...
        'DeltaMeanDegree', NaN, ...
        'DeltaMeanGenerality', NaN, ...
        'DeltaMeanVulnerability', NaN, ...
        'DeltaPropBasal', NaN, ...
        'DeltaPropIntermediate', NaN, ...
        'DeltaPropTop', NaN, ...
        'PseudoTP', NaN, ...
        'PseudoFP', NaN, ...
        'PseudoFN', NaN, ...
        'PseudoTN', NaN, ...
        'PseudoTPR', NaN, ...
        'PseudoTNR', NaN, ...
        'PseudoFPR', NaN, ...
        'PseudoFNR', NaN, ...
        'PseudoPrecision', NaN, ...
        'PseudoRecall', NaN, ...
        'PseudoF1Score', NaN, ...
        'PseudoTSS', NaN, ...
        'PseudoJaccardLinks', NaN, ...
        'NumPredictedNovelLinks', NaN, ...
        'NumTrueNovelLinks', NaN, ...
        'EvaluateOnAllUnseen', 0 ...
    );

    if nargin == 0 || isempty(aux)
        return;
    end

    if isfield(aux, 'comparison_metrics') && ~isempty(aux.comparison_metrics)
        c = aux.comparison_metrics;
        flat.PseudoTP           = safe_field_original(c, 'TP');
        flat.PseudoFP           = safe_field_original(c, 'FP');
        flat.PseudoFN           = safe_field_original(c, 'FN');
        flat.PseudoTN           = safe_field_original(c, 'TN');
        flat.PseudoTPR          = safe_field_original(c, 'TPR');
        flat.PseudoTNR          = safe_field_original(c, 'TNR');
        flat.PseudoFPR          = safe_field_original(c, 'FPR');
        flat.PseudoFNR          = safe_field_original(c, 'FNR');
        flat.PseudoPrecision    = safe_field_original(c, 'Precision');
        flat.PseudoRecall       = safe_field_original(c, 'Recall');
        flat.PseudoF1Score      = safe_field_original(c, 'F1Score');
        flat.PseudoTSS          = safe_field_original(c, 'TSS');
        flat.PseudoJaccardLinks = safe_field_original(c, 'JaccardLinks');
    end

    if isfield(aux, 'NumPredictedNovelLinks')
        flat.NumPredictedNovelLinks = aux.NumPredictedNovelLinks;
    end
    if isfield(aux, 'NumTrueNovelLinks')
        flat.NumTrueNovelLinks = aux.NumTrueNovelLinks;
    end
    if isfield(aux, 'EvaluateOnAllUnseen')
        flat.EvaluateOnAllUnseen = double(aux.EvaluateOnAllUnseen);
    end
end

% ============================================================
% Safe struct field access
% ============================================================
function val = safe_field_original(s, f)
    if isstruct(s) && isfield(s, f) && ~isempty(s.(f))
        val = s.(f);
    else
        val = NaN;
    end
end

function st = make_split_stats_original(train, test)
    totalLinks = nnz(train) + nnz(test);
    st = struct( ...
        'TotalLinks', totalLinks, ...
        'TrainLinks', nnz(train), ...
        'TestLinks', nnz(test), ...
        'BackboneTotal', 0, ...
        'NonBackboneTotal', totalLinks, ...
        'BackboneTrainLinks', 0, ...
        'NonBackboneTrainLinks', nnz(train), ...
        'BackboneTestLinks', 0, ...
        'NonBackboneTestLinks', nnz(test));
end

function st = empty_split_stats_original()
    st = struct( ...
        'TotalLinks', 0, ...
        'TrainLinks', 0, ...
        'TestLinks', 0, ...
        'BackboneTotal', 0, ...
        'NonBackboneTotal', 0, ...
        'BackboneTrainLinks', 0, ...
        'NonBackboneTrainLinks', 0, ...
        'BackboneTestLinks', 0, ...
        'NonBackboneTestLinks', 0);
end

function seed = make_experiment_seed_original(baseSeed, dataname, K, ratioTrain, expID)
    nameHash = sum(double(char(string(dataname))));
    raw = double(baseSeed) ...
        + 1000003 * nameHash ...
        + 1009 * double(K) ...
        + 9173 * round(1000 * double(ratioTrain)) ...
        + double(expID);
    seed = mod(round(raw), 2147483646) + 1;
end

function value = get_config_bool_original(config, field, defaultValue)
    if isfield(config, field) && ~isempty(config.(field))
        value = logical(config.(field));
    else
        value = logical(defaultValue);
    end
end

function value = get_config_number_original(config, field, defaultValue)
    if isfield(config, field) && ~isempty(config.(field))
        value = config.(field);
    else
        value = defaultValue;
    end
end

function value = get_config_text_original(config, field, defaultValue)
    if isfield(config, field) && ~isempty(config.(field))
        value = char(string(config.(field)));
    else
        value = char(string(defaultValue));
    end
end
