function results = run_wlnm_negative(data, K, ratioTrain, config)
    %RUN_WLNM_NEGATIVE Runner for WLNM with directed + negative sampling.
    %
    % INPUTS
    %   data:   struct with fields dataname, net, taxonomy, mass, role
    %   K:      int (subgraph size)
    %   ratioTrain: double in (0,1)
    %   config: struct with fields (nodeSelection, useParallel, numExperiments)
    %
    % OUTPUT
    %   results: struct array with fields:
    %       ROC_AUC, PR_AUC, TimeElapsed, K, TrainRatio, Threshold,
    %       Precision, Recall, F1Score, and split bookkeeping fields

    % Split train/test once per (food web, split ratio)

    [train, test, ~, ~] = DivideNet_negative(data.net, ratioTrain);

    % Split statistics expected by append_results()
    totalLinks = nnz(data.net);
    trainLinks = nnz(train);
    testLinks  = nnz(test);

    % In non-backbone mode, backbone counts are zero and all observed links
    % are treated as non-backbone for bookkeeping purposes.
    splitStats = struct( ...
        'TotalLinks', totalLinks, ...
        'TrainLinks', trainLinks, ...
        'TestLinks', testLinks, ...
        'BackboneTotal', 0, ...
        'NonBackboneTotal', totalLinks, ...
        'BackboneTrainLinks', 0, ...
        'NonBackboneTrainLinks', trainLinks, ...
        'BackboneTestLinks', 0, ...
        'NonBackboneTestLinks', testLinks);

    % Preallocate result objects
    results = repmat(struct( ...
        'ROC_AUC', 0, ...
        'PR_AUC', 0, ...
        'TimeElapsed', '', ...
        'K', K, ...
        'TrainRatio', ratioTrain, ...
        'Threshold', 0, ...
        'Precision', 0, ...
        'Recall', 0, ...
        'F1Score', 0, ...
        'TotalLinks', splitStats.TotalLinks, ...
        'TrainLinks', splitStats.TrainLinks, ...
        'TestLinks', splitStats.TestLinks, ...
        'BackboneTotal', splitStats.BackboneTotal, ...
        'NonBackboneTotal', splitStats.NonBackboneTotal, ...
        'BackboneTrainLinks', splitStats.BackboneTrainLinks, ...
        'NonBackboneTrainLinks', splitStats.NonBackboneTrainLinks, ...
        'BackboneTestLinks', splitStats.BackboneTestLinks, ...
        'NonBackboneTestLinks', splitStats.NonBackboneTestLinks), ...
        config.numExperiments, 1);

    % Broadcast-friendly locals
    dataname      = data.dataname;
    taxonomy      = data.taxonomy;
    mass          = data.mass;
    role          = data.role;
    nodeSelection = config.nodeSelection;

    % Execute experiments
    if config.useParallel
        parfor i = 1:config.numExperiments
            results(i) = one_experiment_negative( ...
                i, dataname, train, test, K, ratioTrain, ...
                taxonomy, mass, role, nodeSelection, splitStats);
        end
    else
        for i = 1:config.numExperiments
            results(i) = one_experiment_negative( ...
                i, dataname, train, test, K, ratioTrain, ...
                taxonomy, mass, role, nodeSelection, splitStats);
        end
    end
end

function r = one_experiment_negative(i, dataname, train, test, K, ratioTrain, taxonomy, mass, role, nodeSelection, splitStats)

    t0 = tic;
    disp(['Experiment ', num2str(i), ' (node selection: ', char(nodeSelection), ') - Running WLNM_negative...']);

    [roc_auc, pr_auc, best_threshold, best_precision, best_recall, best_f1_score] = ...
        WLNM_negative(dataname, train, test, K, taxonomy, mass, role, nodeSelection, ratioTrain);

    r = struct( ...
        'ROC_AUC', roc_auc, ...
        'PR_AUC', pr_auc, ...
        'TimeElapsed', datestr(seconds(toc(t0)), 'HH:MM:SS'), ...
        'K', K, ...
        'TrainRatio', ratioTrain, ...
        'Threshold', best_threshold, ...
        'Precision', best_precision, ...
        'Recall', best_recall, ...
        'F1Score', best_f1_score, ...
        'TotalLinks', splitStats.TotalLinks, ...
        'TrainLinks', splitStats.TrainLinks, ...
        'TestLinks', splitStats.TestLinks, ...
        'BackboneTotal', splitStats.BackboneTotal, ...
        'NonBackboneTotal', splitStats.NonBackboneTotal, ...
        'BackboneTrainLinks', splitStats.BackboneTrainLinks, ...
        'NonBackboneTrainLinks', splitStats.NonBackboneTrainLinks, ...
        'BackboneTestLinks', splitStats.BackboneTestLinks, ...
        'NonBackboneTestLinks', splitStats.NonBackboneTestLinks);
end
