function results = run_wlnm_negative(data, K, ratioTrain, config)
    %RUN_WLNM_NEGATIVE Runner for WLNM with negative sampling.

    [train, test, ~, ~] = DivideNet_negative(data.net, ratioTrain);

    % Split statistics
    totalLinks = nnz(data.net);
    trainLinks = nnz(train);
    testLinks  = nnz(test);

    splitStats = struct( ...
        'TotalLinks', totalLinks, ...
        'TrainLinks', trainLinks, ...
        'TestLinks', testLinks, ...
        'BackboneTotal', 0, ...
        'NonBackboneTotal', totalLinks, ...
        'BackboneTrainLinks', 0, ...
        'NonBackboneTrainLinks', trainLinks, ...
        'BackboneTestLinks', 0, ...
        'NonBackboneTestLinks', testLinks);

    % Preallocate result objects with extended CSV schema
    results = repmat(make_result_template_negative(K, ratioTrain, splitStats), ...
        config.numExperiments, 1);

    % Broadcast-friendly locals
    dataname      = data.dataname;
    taxonomy      = data.taxonomy;
    mass          = data.mass;
    role          = data.role;
    nodeSelection = config.nodeSelection;

    % Execute experiments
    if config.useParallel
        parfor i = 1:config.numExperiments
            results(i) = one_experiment_negative( ...
                i, dataname, train, test, K, ratioTrain, ...
                taxonomy, mass, role, nodeSelection, splitStats);
        end
    else
        for i = 1:config.numExperiments
            results(i) = one_experiment_negative( ...
                i, dataname, train, test, K, ratioTrain, ...
                taxonomy, mass, role, nodeSelection, splitStats);
        end
    end
end

function r = one_experiment_negative(i, dataname, train, test, K, ratioTrain, taxonomy, mass, role, nodeSelection, splitStats)

    t0 = tic;
    disp(['Experiment ', num2str(i), ' (node selection: ', char(nodeSelection), ') - Running WLNM_negative...']);

    [roc_auc, pr_auc, best_threshold, best_precision, best_recall, best_f1_score, aux] = ...
        WLNM_negative(dataname, train, test, K, taxonomy, mass, role, nodeSelection, ratioTrain);

    r = make_result_template_negative(K, ratioTrain, splitStats);
    r = populate_result_row_negative( ...
        r, roc_auc, pr_auc, best_threshold, best_precision, best_recall, ...
        best_f1_score, toc(t0), aux);
end

% ============================================================
% Result row template
% ============================================================
function out = make_result_template_negative(K, ratioTrain, splitStats)
    out = struct( ...
        'ROC_AUC', 0, ...
        'PR_AUC', 0, ...
        'TimeElapsed', '', ...
        'K', K, ...
        'TrainRatio', ratioTrain, ...
        'Threshold', 0, ...
        'Precision', 0, ...
        'Recall', 0, ...
        'F1Score', 0, ...
        'TotalLinks', splitStats.TotalLinks, ...
        'TrainLinks', splitStats.TrainLinks, ...
        'TestLinks', splitStats.TestLinks, ...
        'BackboneTotal', splitStats.BackboneTotal, ...
        'NonBackboneTotal', splitStats.NonBackboneTotal, ...
        'BackboneTrainLinks', splitStats.BackboneTrainLinks, ...
        'NonBackboneTrainLinks', splitStats.NonBackboneTrainLinks, ...
        'BackboneTestLinks', splitStats.BackboneTestLinks, ...
        'NonBackboneTestLinks', splitStats.NonBackboneTestLinks, ...
        'EmpiricalNumSpecies', NaN, ...
        'EmpiricalLinks', NaN, ...
        'EmpiricalConnectance', NaN, ...
        'EmpiricalMeanTrophicLevel', NaN, ...
        'EmpiricalMeanDegree', NaN, ...
        'EmpiricalMeanGenerality', NaN, ...
        'EmpiricalMeanVulnerability', NaN, ...
        'EmpiricalPropBasal', NaN, ...
        'EmpiricalPropIntermediate', NaN, ...
        'EmpiricalPropTop', NaN, ...
        'PseudoNumSpecies', NaN, ...
        'PseudoLinks', NaN, ...
        'PseudoConnectance', NaN, ...
        'PseudoMeanTrophicLevel', NaN, ...
        'PseudoMeanDegree', NaN, ...
        'PseudoMeanGenerality', NaN, ...
        'PseudoMeanVulnerability', NaN, ...
        'PseudoPropBasal', NaN, ...
        'PseudoPropIntermediate', NaN, ...
        'PseudoPropTop', NaN, ...
        'DeltaLinks', NaN, ...
        'DeltaConnectance', NaN, ...
        'DeltaMeanTrophicLevel', NaN, ...
        'DeltaMeanDegree', NaN, ...
        'DeltaMeanGenerality', NaN, ...
        'DeltaMeanVulnerability', NaN, ...
        'DeltaPropBasal', NaN, ...
        'DeltaPropIntermediate', NaN, ...
        'DeltaPropTop', NaN, ...
        'PseudoTP', NaN, ...
        'PseudoFP', NaN, ...
        'PseudoFN', NaN, ...
        'PseudoTN', NaN, ...
        'PseudoTPR', NaN, ...
        'PseudoTNR', NaN, ...
        'PseudoFPR', NaN, ...
        'PseudoFNR', NaN, ...
        'PseudoPrecision', NaN, ...
        'PseudoRecall', NaN, ...
        'PseudoF1Score', NaN, ...
        'PseudoTSS', NaN, ...
        'PseudoJaccardLinks', NaN, ...
        'NumPredictedNovelLinks', NaN, ...
        'NumTrueNovelLinks', NaN, ...
        'EvaluateOnAllUnseen', 0 ...
    );
end

% ============================================================
% Fill predictive + auxiliary metrics into result row
% ============================================================
function out = populate_result_row_negative(out, roc_auc, pr_auc, thr, prec, rec, f1, elapsed_seconds, aux)
    out.ROC_AUC     = roc_auc;
    out.PR_AUC      = pr_auc;
    out.TimeElapsed = datestr(seconds(elapsed_seconds), 'HH:MM:SS');
    out.Threshold   = thr;
    out.Precision   = prec;
    out.Recall      = rec;
    out.F1Score     = f1;

    flat = flatten_aux_metrics_negative(aux);
    fn = fieldnames(flat);
    for k = 1:numel(fn)
        out.(fn{k}) = flat.(fn{k});
    end
end

% ============================================================
% Flatten aux struct into scalar CSV fields
% ============================================================
function flat = flatten_aux_metrics_negative(aux)

    flat = struct( ...
        'EmpiricalNumSpecies', NaN, ...
        'EmpiricalLinks', NaN, ...
        'EmpiricalConnectance', NaN, ...
        'EmpiricalMeanTrophicLevel', NaN, ...
        'EmpiricalMeanDegree', NaN, ...
        'EmpiricalMeanGenerality', NaN, ...
        'EmpiricalMeanVulnerability', NaN, ...
        'EmpiricalPropBasal', NaN, ...
        'EmpiricalPropIntermediate', NaN, ...
        'EmpiricalPropTop', NaN, ...
        'PseudoNumSpecies', NaN, ...
        'PseudoLinks', NaN, ...
        'PseudoConnectance', NaN, ...
        'PseudoMeanTrophicLevel', NaN, ...
        'PseudoMeanDegree', NaN, ...
        'PseudoMeanGenerality', NaN, ...
        'PseudoMeanVulnerability', NaN, ...
        'PseudoPropBasal', NaN, ...
        'PseudoPropIntermediate', NaN, ...
        'PseudoPropTop', NaN, ...
        'DeltaLinks', NaN, ...
        'DeltaConnectance', NaN, ...
        'DeltaMeanTrophicLevel', NaN, ...
        'DeltaMeanDegree', NaN, ...
        'DeltaMeanGenerality', NaN, ...
        'DeltaMeanVulnerability', NaN, ...
        'DeltaPropBasal', NaN, ...
        'DeltaPropIntermediate', NaN, ...
        'DeltaPropTop', NaN, ...
        'PseudoTP', NaN, ...
        'PseudoFP', NaN, ...
        'PseudoFN', NaN, ...
        'PseudoTN', NaN, ...
        'PseudoTPR', NaN, ...
        'PseudoTNR', NaN, ...
        'PseudoFPR', NaN, ...
        'PseudoFNR', NaN, ...
        'PseudoPrecision', NaN, ...
        'PseudoRecall', NaN, ...
        'PseudoF1Score', NaN, ...
        'PseudoTSS', NaN, ...
        'PseudoJaccardLinks', NaN, ...
        'NumPredictedNovelLinks', NaN, ...
        'NumTrueNovelLinks', NaN, ...
        'EvaluateOnAllUnseen', 0 ...
    );

    if nargin == 0 || isempty(aux)
        return;
    end

    if isfield(aux, 'comparison_metrics') && ~isempty(aux.comparison_metrics)
        c = aux.comparison_metrics;
        flat.PseudoTP           = safe_field_negative(c, 'TP');
        flat.PseudoFP           = safe_field_negative(c, 'FP');
        flat.PseudoFN           = safe_field_negative(c, 'FN');
        flat.PseudoTN           = safe_field_negative(c, 'TN');
        flat.PseudoTPR          = safe_field_negative(c, 'TPR');
        flat.PseudoTNR          = safe_field_negative(c, 'TNR');
        flat.PseudoFPR          = safe_field_negative(c, 'FPR');
        flat.PseudoFNR          = safe_field_negative(c, 'FNR');
        flat.PseudoPrecision    = safe_field_negative(c, 'Precision');
        flat.PseudoRecall       = safe_field_negative(c, 'Recall');
        flat.PseudoF1Score      = safe_field_negative(c, 'F1Score');
        flat.PseudoTSS          = safe_field_negative(c, 'TSS');
        flat.PseudoJaccardLinks = safe_field_negative(c, 'JaccardLinks');
    end

    if isfield(aux, 'NumPredictedNovelLinks')
        flat.NumPredictedNovelLinks = aux.NumPredictedNovelLinks;
    end
    if isfield(aux, 'NumTrueNovelLinks')
        flat.NumTrueNovelLinks = aux.NumTrueNovelLinks;
    end
    if isfield(aux, 'EvaluateOnAllUnseen')
        flat.EvaluateOnAllUnseen = double(aux.EvaluateOnAllUnseen);
    end
end

% ============================================================
% Safe struct field access
% ============================================================
function val = safe_field_negative(s, f)
    if isstruct(s) && isfield(s, f) && ~isempty(s.(f))
        val = s.(f);
    else
        val = NaN;
    end
end
