function results = run_wlnm_directed(data, K, ratioTrain, config)
    %RUN_WLNM_DIRECTED Runner for WLNM with directed sampling.

    % Preallocate result objects with extended CSV schema
    results = repmat(make_result_template_directed(K, ratioTrain, empty_split_stats(), config, 0, 0), ...
        config.numExperiments, 1);

    % Broadcast-friendly locals
    dataname      = data.dataname;
    net           = data.net;
    taxonomy      = data.taxonomy;
    mass          = data.mass;
    role          = data.role;
    nodeSelection = config.nodeSelection;
    baseSeed      = get_config_number_directed(config, 'baseSeed', 12345);
    resampleSplits = get_config_bool_directed(config, 'resampleSplitsEachExperiment', true);
    saveAux = get_config_bool_directed(config, 'exportAuxiliaryCSVs', false);
    artifactDir = get_config_text_directed(config, 'artifactDir', 'data/result/confusion_matrix_csv/');
    thresholdMode = get_config_text_directed(config, 'thresholdMode', 'fixed');
    fixedThreshold = get_config_number_directed(config, 'fixedThreshold', 0.5);
    evaluateOnAllUnseen = get_config_bool_directed(config, 'evaluate_on_all_unseen', false);
    encodeParallel = get_config_bool_directed(config, 'useGraphEncodingParallel', false) && ~logical(config.useParallel);
    computeEcologicalMetrics = get_config_bool_directed(config, 'computeEcologicalMetrics', true);

    sharedTrain = [];
    sharedTest = [];
    sharedStats = [];
    if ~resampleSplits
        splitSeed = make_experiment_seed_directed(baseSeed, dataname, K, ratioTrain, 0);
        rng(splitSeed, 'twister');
        [sharedTrain, sharedTest, ~, ~] = DivideNet_directed(net, ratioTrain);
        sharedStats = make_split_stats_directed(sharedTrain, sharedTest);
    end

    % Execute experiments
    if config.useParallel
        startIdx = 1;
        if saveAux
            results(1) = one_experiment_directed( ...
                1, baseSeed, dataname, net, K, ratioTrain, taxonomy, mass, role, ...
                nodeSelection, config, sharedTrain, sharedTest, sharedStats, true, ...
                artifactDir, thresholdMode, fixedThreshold, evaluateOnAllUnseen, ...
                encodeParallel, computeEcologicalMetrics);
            startIdx = 2;
        end

        if startIdx <= config.numExperiments
            parfor i = startIdx:config.numExperiments
                results(i) = one_experiment_directed( ...
                    i, baseSeed, dataname, net, K, ratioTrain, taxonomy, mass, role, ...
                    nodeSelection, config, sharedTrain, sharedTest, sharedStats, false, ...
                    artifactDir, thresholdMode, fixedThreshold, evaluateOnAllUnseen, ...
                    encodeParallel, computeEcologicalMetrics);
            end
        end
    else
        for i = 1:config.numExperiments
            results(i) = one_experiment_directed( ...
                i, baseSeed, dataname, net, K, ratioTrain, taxonomy, mass, role, ...
                nodeSelection, config, sharedTrain, sharedTest, sharedStats, saveAux && i == 1, ...
                artifactDir, thresholdMode, fixedThreshold, evaluateOnAllUnseen, ...
                encodeParallel, computeEcologicalMetrics);
        end
    end
end

function r = one_experiment_directed(i, baseSeed, dataname, net, K, ratioTrain, taxonomy, mass, role, ...
        nodeSelection, config, sharedTrain, sharedTest, sharedStats, saveConfusion, artifactDir, ...
        thresholdMode, fixedThreshold, evaluateOnAllUnseen, encodeParallel, computeEcologicalMetrics)

    seed = make_experiment_seed_directed(baseSeed, dataname, K, ratioTrain, i);
    rng(seed, 'twister');

    if isempty(sharedTrain)
        [train, test, ~, ~] = DivideNet_directed(net, ratioTrain);
        splitStats = make_split_stats_directed(train, test);
    else
        train = sharedTrain;
        test = sharedTest;
        splitStats = sharedStats;
    end

    t0 = tic;
    disp(['Experiment ', num2str(i), ' (node selection: ', char(nodeSelection), ') - Running WLNM_directed...']);

    artifactTag = sprintf('%s_exp%03d_seed%d', lower(get_config_text_directed(config, 'version', 'WLNM_directed')), i, seed);

    [roc_auc, pr_auc, best_threshold, best_precision, best_recall, best_f1_score, aux] = ...
        WLNM_directed(dataname, train, test, K, taxonomy, mass, role, nodeSelection, ratioTrain, ...
            'save_confusion', saveConfusion, ...
            'artifact_tag', artifactTag, ...
            'artifact_dir', artifactDir, ...
            'threshold_mode', thresholdMode, ...
            'fixed_threshold', fixedThreshold, ...
            'ith_experiment', i, ...
            'evaluate_on_all_unseen', evaluateOnAllUnseen, ...
            'encode_parallel', encodeParallel, ...
            'compute_ecological_metrics', computeEcologicalMetrics);

    r = make_result_template_directed(K, ratioTrain, splitStats, config, i, seed);
    r = populate_result_row_directed( ...
        r, roc_auc, pr_auc, best_threshold, best_precision, best_recall, ...
        best_f1_score, toc(t0), aux);
end

% ============================================================
% Result row template
% ============================================================
function out = make_result_template_directed(K, ratioTrain, splitStats, config, expID, seed)
    if nargin < 4 || isempty(config)
        config = struct();
    end
    if nargin < 5
        expID = 0;
    end
    if nargin < 6
        seed = 0;
    end

    out = struct( ...
        'Version', get_config_text_directed(config, 'version', 'WLNM_directed'), ...
        'ROC_AUC', 0, ...
        'PR_AUC', 0, ...
        'TimeElapsed', '', ...
        'K', K, ...
        'TrainRatio', ratioTrain, ...
        'ExperimentID', expID, ...
        'Seed', seed, ...
        'ThresholdMode', get_config_text_directed(config, 'thresholdMode', 'fixed'), ...
        'CvK', 0, ...
        'FoldID', 0, ...
        'NumFolds', 0, ...
        'Threshold', 0, ...
        'Precision', 0, ...
        'Recall', 0, ...
        'F1Score', 0, ...
        'TestTP', NaN, ...
        'TestFP', NaN, ...
        'TestFN', NaN, ...
        'TestTN', NaN, ...
        'TestTPR', NaN, ...
        'TestTNR', NaN, ...
        'TestFPR', NaN, ...
        'TestFNR', NaN, ...
        'TestPrecision', NaN, ...
        'TestRecall', NaN, ...
        'TestF1Score', NaN, ...
        'TestAccuracy', NaN, ...
        'TestExpectedAccuracy', NaN, ...
        'TestKappa', NaN, ...
        'TestMCC', NaN, ...
        'TestTSS', NaN, ...
        'TotalLinks', splitStats.TotalLinks, ...
        'TrainLinks', splitStats.TrainLinks, ...
        'TestLinks', splitStats.TestLinks, ...
        'BackboneTotal', splitStats.BackboneTotal, ...
        'NonBackboneTotal', splitStats.NonBackboneTotal, ...
        'BackboneTrainLinks', splitStats.BackboneTrainLinks, ...
        'NonBackboneTrainLinks', splitStats.NonBackboneTrainLinks, ...
        'BackboneTestLinks', splitStats.BackboneTestLinks, ...
        'NonBackboneTestLinks', splitStats.NonBackboneTestLinks, ...
        'EmpiricalNumSpecies', NaN, ...
        'EmpiricalLinks', NaN, ...
        'EmpiricalConnectance', NaN, ...
        'EmpiricalMeanTrophicLevel', NaN, ...
        'EmpiricalMeanDegree', NaN, ...
        'EmpiricalMeanGenerality', NaN, ...
        'EmpiricalMeanVulnerability', NaN, ...
        'EmpiricalPropBasal', NaN, ...
        'EmpiricalPropIntermediate', NaN, ...
        'EmpiricalPropTop', NaN, ...
        'PseudoNumSpecies', NaN, ...
        'PseudoLinks', NaN, ...
        'PseudoConnectance', NaN, ...
        'PseudoMeanTrophicLevel', NaN, ...
        'PseudoMeanDegree', NaN, ...
        'PseudoMeanGenerality', NaN, ...
        'PseudoMeanVulnerability', NaN, ...
        'PseudoPropBasal', NaN, ...
        'PseudoPropIntermediate', NaN, ...
        'PseudoPropTop', NaN, ...
        'DeltaLinks', NaN, ...
        'DeltaConnectance', NaN, ...
        'DeltaMeanTrophicLevel', NaN, ...
        'DeltaMeanDegree', NaN, ...
        'DeltaMeanGenerality', NaN, ...
        'DeltaMeanVulnerability', NaN, ...
        'DeltaPropBasal', NaN, ...
        'DeltaPropIntermediate', NaN, ...
        'DeltaPropTop', NaN, ...
        'PseudoTP', NaN, ...
        'PseudoFP', NaN, ...
        'PseudoFN', NaN, ...
        'PseudoTN', NaN, ...
        'PseudoTPR', NaN, ...
        'PseudoTNR', NaN, ...
        'PseudoFPR', NaN, ...
        'PseudoFNR', NaN, ...
        'PseudoPrecision', NaN, ...
        'PseudoRecall', NaN, ...
        'PseudoF1Score', NaN, ...
        'PseudoMCC', NaN, ...
        'PseudoTSS', NaN, ...
        'PseudoJaccardLinks', NaN, ...
        'NumPredictedNovelLinks', NaN, ...
        'NumTrueNovelLinks', NaN, ...
        'EvaluateOnAllUnseen', NaN ...
    );
end

% ============================================================
% Fill predictive + ecological metrics into result row
% ============================================================
function out = populate_result_row_directed(out, roc_auc, pr_auc, thr, prec, rec, f1, elapsed_seconds, aux)

    out.ROC_AUC     = roc_auc;
    out.PR_AUC      = pr_auc;
    out.TimeElapsed = datestr(seconds(elapsed_seconds), 'HH:MM:SS');
    out.Threshold   = thr;
    out.Precision   = prec;
    out.Recall      = rec;
    out.F1Score     = f1;

    flat = flatten_aux_metrics_directed(aux);
    fn = fieldnames(flat);
    for k = 1:numel(fn)
        out.(fn{k}) = flat.(fn{k});
    end
end

% ============================================================
% Flatten aux struct from WLNM_directed into scalar fields
% ============================================================
function flat = flatten_aux_metrics_directed(aux)

    flat = struct( ...
        'EmpiricalNumSpecies', NaN, ...
        'EmpiricalLinks', NaN, ...
        'EmpiricalConnectance', NaN, ...
        'EmpiricalMeanTrophicLevel', NaN, ...
        'EmpiricalMeanDegree', NaN, ...
        'EmpiricalMeanGenerality', NaN, ...
        'EmpiricalMeanVulnerability', NaN, ...
        'EmpiricalPropBasal', NaN, ...
        'EmpiricalPropIntermediate', NaN, ...
        'EmpiricalPropTop', NaN, ...
        'PseudoNumSpecies', NaN, ...
        'PseudoLinks', NaN, ...
        'PseudoConnectance', NaN, ...
        'PseudoMeanTrophicLevel', NaN, ...
        'PseudoMeanDegree', NaN, ...
        'PseudoMeanGenerality', NaN, ...
        'PseudoMeanVulnerability', NaN, ...
        'PseudoPropBasal', NaN, ...
        'PseudoPropIntermediate', NaN, ...
        'PseudoPropTop', NaN, ...
        'DeltaLinks', NaN, ...
        'DeltaConnectance', NaN, ...
        'DeltaMeanTrophicLevel', NaN, ...
        'DeltaMeanDegree', NaN, ...
        'DeltaMeanGenerality', NaN, ...
        'DeltaMeanVulnerability', NaN, ...
        'DeltaPropBasal', NaN, ...
        'DeltaPropIntermediate', NaN, ...
        'DeltaPropTop', NaN, ...
        'TestTP', NaN, ...
        'TestFP', NaN, ...
        'TestFN', NaN, ...
        'TestTN', NaN, ...
        'TestTPR', NaN, ...
        'TestTNR', NaN, ...
        'TestFPR', NaN, ...
        'TestFNR', NaN, ...
        'TestPrecision', NaN, ...
        'TestRecall', NaN, ...
        'TestF1Score', NaN, ...
        'TestAccuracy', NaN, ...
        'TestExpectedAccuracy', NaN, ...
        'TestKappa', NaN, ...
        'TestMCC', NaN, ...
        'TestTSS', NaN, ...
        'PseudoTP', NaN, ...
        'PseudoFP', NaN, ...
        'PseudoFN', NaN, ...
        'PseudoTN', NaN, ...
        'PseudoTPR', NaN, ...
        'PseudoTNR', NaN, ...
        'PseudoFPR', NaN, ...
        'PseudoFNR', NaN, ...
        'PseudoPrecision', NaN, ...
        'PseudoRecall', NaN, ...
        'PseudoF1Score', NaN, ...
        'PseudoMCC', NaN, ...
        'PseudoTSS', NaN, ...
        'PseudoJaccardLinks', NaN, ...
        'NumPredictedNovelLinks', NaN, ...
        'NumTrueNovelLinks', NaN, ...
        'EvaluateOnAllUnseen', NaN ...
    );

    if nargin == 0 || isempty(aux)
        return;
    end

    % ---- empirical metrics ----
    if isfield(aux, 'empirical_metrics') && ~isempty(aux.empirical_metrics)
        m = aux.empirical_metrics;
        flat.EmpiricalNumSpecies        = safe_field_directed(m, 'NumSpecies');
        flat.EmpiricalLinks             = safe_field_directed(m, 'NumLinks');
        flat.EmpiricalConnectance       = safe_field_directed(m, 'Connectance');
        flat.EmpiricalMeanTrophicLevel  = safe_field_directed(m, 'MeanTrophicLevel');
        flat.EmpiricalMeanDegree        = safe_field_directed(m, 'MeanDegree');
        flat.EmpiricalMeanGenerality    = safe_field_directed(m, 'MeanGenerality');
        flat.EmpiricalMeanVulnerability = safe_field_directed(m, 'MeanVulnerability');
        flat.EmpiricalPropBasal         = safe_field_directed(m, 'PropBasal');
        flat.EmpiricalPropIntermediate  = safe_field_directed(m, 'PropIntermediate');
        flat.EmpiricalPropTop           = safe_field_directed(m, 'PropTop');
    end

    % ---- pseudo metrics ----
    if isfield(aux, 'pseudo_metrics') && ~isempty(aux.pseudo_metrics)
        m = aux.pseudo_metrics;
        flat.PseudoNumSpecies        = safe_field_directed(m, 'NumSpecies');
        flat.PseudoLinks             = safe_field_directed(m, 'NumLinks');
        flat.PseudoConnectance       = safe_field_directed(m, 'Connectance');
        flat.PseudoMeanTrophicLevel  = safe_field_directed(m, 'MeanTrophicLevel');
        flat.PseudoMeanDegree        = safe_field_directed(m, 'MeanDegree');
        flat.PseudoMeanGenerality    = safe_field_directed(m, 'MeanGenerality');
        flat.PseudoMeanVulnerability = safe_field_directed(m, 'MeanVulnerability');
        flat.PseudoPropBasal         = safe_field_directed(m, 'PropBasal');
        flat.PseudoPropIntermediate  = safe_field_directed(m, 'PropIntermediate');
        flat.PseudoPropTop           = safe_field_directed(m, 'PropTop');
    end

    % ---- deltas ----
    flat.DeltaLinks             = flat.PseudoLinks             - flat.EmpiricalLinks;
    flat.DeltaConnectance       = flat.PseudoConnectance       - flat.EmpiricalConnectance;
    flat.DeltaMeanTrophicLevel  = flat.PseudoMeanTrophicLevel  - flat.EmpiricalMeanTrophicLevel;
    flat.DeltaMeanDegree        = flat.PseudoMeanDegree        - flat.EmpiricalMeanDegree;
    flat.DeltaMeanGenerality    = flat.PseudoMeanGenerality    - flat.EmpiricalMeanGenerality;
    flat.DeltaMeanVulnerability = flat.PseudoMeanVulnerability - flat.EmpiricalMeanVulnerability;
    flat.DeltaPropBasal         = flat.PseudoPropBasal         - flat.EmpiricalPropBasal;
    flat.DeltaPropIntermediate  = flat.PseudoPropIntermediate  - flat.EmpiricalPropIntermediate;
    flat.DeltaPropTop           = flat.PseudoPropTop           - flat.EmpiricalPropTop;

    % ---- test-set classification metrics ----
    if isfield(aux, 'test_metrics') && ~isempty(aux.test_metrics)
        t = aux.test_metrics;
        flat.TestTP               = safe_field_directed(t, 'TP');
        flat.TestFP               = safe_field_directed(t, 'FP');
        flat.TestFN               = safe_field_directed(t, 'FN');
        flat.TestTN               = safe_field_directed(t, 'TN');
        flat.TestTPR              = safe_field_directed(t, 'TPR');
        flat.TestTNR              = safe_field_directed(t, 'TNR');
        flat.TestFPR              = safe_field_directed(t, 'FPR');
        flat.TestFNR              = safe_field_directed(t, 'FNR');
        flat.TestPrecision        = safe_field_directed(t, 'Precision');
        flat.TestRecall           = safe_field_directed(t, 'Recall');
        flat.TestF1Score          = safe_field_directed(t, 'F1Score');
        flat.TestAccuracy         = safe_field_directed(t, 'Accuracy');
        flat.TestExpectedAccuracy = safe_field_directed(t, 'ExpectedAccuracy');
        flat.TestKappa            = safe_field_directed(t, 'Kappa');
        flat.TestMCC              = safe_field_directed(t, 'MCC');
        flat.TestTSS              = safe_field_directed(t, 'TSS');
    end

    % ---- comparison metrics ----
    if isfield(aux, 'comparison_metrics') && ~isempty(aux.comparison_metrics)
        c = aux.comparison_metrics;
        flat.PseudoTP           = safe_field_directed(c, 'TP');
        flat.PseudoFP           = safe_field_directed(c, 'FP');
        flat.PseudoFN           = safe_field_directed(c, 'FN');
        flat.PseudoTN           = safe_field_directed(c, 'TN');
        flat.PseudoTPR          = safe_field_directed(c, 'TPR');
        flat.PseudoTNR          = safe_field_directed(c, 'TNR');
        flat.PseudoFPR          = safe_field_directed(c, 'FPR');
        flat.PseudoFNR          = safe_field_directed(c, 'FNR');
        flat.PseudoPrecision    = safe_field_directed(c, 'Precision');
        flat.PseudoRecall       = safe_field_directed(c, 'Recall');
        flat.PseudoF1Score      = safe_field_directed(c, 'F1Score');
        flat.PseudoMCC          = safe_field_directed(c, 'MCC');
        flat.PseudoTSS          = safe_field_directed(c, 'TSS');
        flat.PseudoJaccardLinks = safe_field_directed(c, 'JaccardLinks');
    end

    % ---- bookkeeping ----
    if isfield(aux, 'NumPredictedNovelLinks')
        flat.NumPredictedNovelLinks = aux.NumPredictedNovelLinks;
    end
    if isfield(aux, 'NumTrueNovelLinks')
        flat.NumTrueNovelLinks = aux.NumTrueNovelLinks;
    end
    if isfield(aux, 'EvaluateOnAllUnseen')
        flat.EvaluateOnAllUnseen = double(aux.EvaluateOnAllUnseen);
    end
end

% ============================================================
% Safe struct field access
% ============================================================
function val = safe_field_directed(s, f)
    if isstruct(s) && isfield(s, f) && ~isempty(s.(f))
        val = s.(f);
    else
        val = NaN;
    end
end

function st = make_split_stats_directed(train, test)
    totalLinks = nnz(train) + nnz(test);
    st = struct( ...
        'TotalLinks', totalLinks, ...
        'TrainLinks', nnz(train), ...
        'TestLinks', nnz(test), ...
        'BackboneTotal', 0, ...
        'NonBackboneTotal', totalLinks, ...
        'BackboneTrainLinks', 0, ...
        'NonBackboneTrainLinks', nnz(train), ...
        'BackboneTestLinks', 0, ...
        'NonBackboneTestLinks', nnz(test));
end

function st = empty_split_stats()
    st = struct( ...
        'TotalLinks', 0, ...
        'TrainLinks', 0, ...
        'TestLinks', 0, ...
        'BackboneTotal', 0, ...
        'NonBackboneTotal', 0, ...
        'BackboneTrainLinks', 0, ...
        'NonBackboneTrainLinks', 0, ...
        'BackboneTestLinks', 0, ...
        'NonBackboneTestLinks', 0);
end

function seed = make_experiment_seed_directed(baseSeed, dataname, K, ratioTrain, expID)
    nameHash = sum(double(char(string(dataname))));
    raw = double(baseSeed) ...
        + 1000003 * nameHash ...
        + 1009 * double(K) ...
        + 9173 * round(1000 * double(ratioTrain)) ...
        + double(expID);
    seed = mod(round(raw), 2147483646) + 1;
end

function value = get_config_bool_directed(config, field, defaultValue)
    if isfield(config, field) && ~isempty(config.(field))
        value = logical(config.(field));
    else
        value = logical(defaultValue);
    end
end

function value = get_config_number_directed(config, field, defaultValue)
    if isfield(config, field) && ~isempty(config.(field))
        value = config.(field);
    else
        value = defaultValue;
    end
end

function value = get_config_text_directed(config, field, defaultValue)
    if isfield(config, field) && ~isempty(config.(field))
        value = char(string(config.(field)));
    else
        value = char(string(defaultValue));
    end
end
