function tests = test_wlnm_dir_neg_protocol_logging
%TEST_WLNM_DIR_NEG_PROTOCOL_LOGGING Verify sampler metadata reaches the CSV.
    tests = functiontests(localfunctions);
end

function testKfoldProtocolColumnsAreWritten(testCase)
    output_dir = tempname;
    mkdir(output_dir);
    cleanup = onCleanup(@() rmdir(output_dir, 's')); %#ok<NASGU>
    log_file = fullfile(output_dir, 'kfold_role_only.csv');

    init_log_file(log_file, false, false, 'WLNM_dir_neg_kfold');
    result = struct( ...
        'Version', 'WLNM_dir_neg_kfold', ...
        'TrainRatio', 0.80, ...
        'ExperimentID', 1, ...
        'Seed', 13346, ...
        'ThresholdMode', 'fixed', ...
        'TrophicLevelProtocol', 'validated_v2', ...
        'TrophicSnapshotFile', '/tmp/example_snapshot.mat', ...
        'PseudoTrophicV2FailureReason', 'ok', ...
        'PseudoTrophicV2LegacyMean', 2.5, ...
        'PseudoTrophicV2LegacyStatusCode', 0, ...
        'NegativeEligibilityMode', 'role_only', ...
        'NegativePositiveRatio', 2, ...
        'NegativeSamplingStrategy', 'uniform_without_replacement', ...
        'NegativeTopupPolicy', 'uniform_remaining_nonlinks', ...
        'MassPoolSize', 0, ...
        'CvK', 5, ...
        'FoldID', 1, ...
        'NumFolds', 5);
    append_results(log_file, result, false);

    output = readtable(log_file, 'VariableNamingRule', 'preserve');
    verifyEqual(testCase, height(output), 1);
    verifyEqual(testCase, string(output.TrophicLevelProtocol), "validated_v2");
    verifyEqual(testCase, string(output.NegativeEligibilityMode), "role_only");
    verifyEqual(testCase, output.NegativePositiveRatio, 2);
    verifyEqual(testCase, output.MassPoolSize, 0);
    verifyEqual(testCase, output.CvK, 5);
    verifyFalse(testCase, any(ismember( ...
        expected_normalized_gv_columns(), output.Properties.VariableNames)));
end

function testRoleOnlyProtocolColumnsAreWritten(testCase)
    output_dir = tempname;
    mkdir(output_dir);
    cleanup = onCleanup(@() rmdir(output_dir, 's')); %#ok<NASGU>
    log_file = fullfile(output_dir, 'role_only.csv');

    init_log_file(log_file, false, false, 'WLNM_dir_neg');

    result = struct( ...
        'Version', 'WLNM_dir_neg', ...
        'TrainRatio', 0.60, ...
        'ExperimentID', 1, ...
        'Seed', 123, ...
        'ThresholdMode', 'fixed', ...
        'TrophicLevelProtocol', 'validated_v2', ...
        'TrophicSnapshotFile', '/tmp/example_snapshot.mat', ...
        'PseudoTrophicV2FailureReason', 'ok', ...
        'PseudoTrophicV2LegacyMean', 2.5, ...
        'PseudoTrophicV2LegacyStatusCode', 0, ...
        'Threshold', 0.50, ...
        'NegativeEligibilityMode', 'role_only', ...
        'NegativePositiveRatio', 2, ...
        'NegativeSamplingStrategy', 'uniform_without_replacement', ...
        'NegativeTopupPolicy', 'uniform_remaining_nonlinks', ...
        'RolePoolSize', 28, ...
        'MassPoolSize', 0, ...
        'EligiblePoolSize', 28, ...
        'FullNegativePoolSize', 90, ...
        'RequestedNegativeCount', 40, ...
        'SelectedNegativeCount', 40, ...
        'EligibleNegativeCount', 28, ...
        'EligibleShortfall', 12, ...
        'FullPoolShortfall', 0, ...
        'RandomTopupCount', 12, ...
        'TopupProportion', 0.30, ...
        'TrainNegativeCount', 24, ...
        'TestNegativeCount', 16 ...
    );

    normalized_cols = expected_normalized_gv_columns();
    normalized_values = (1:numel(normalized_cols)) / 10;
    for i = 1:numel(normalized_cols)
        result.(normalized_cols{i}) = normalized_values(i);
    end

    % Reopening a current-schema log is allowed and leaves it unchanged.
    init_log_file(log_file, false, false, 'WLNM_dir_neg');
    append_results(log_file, result, false);

    output = readtable(log_file, 'VariableNamingRule', 'preserve');
    verifyEqual(testCase, height(output), 1);
    verifyEqual(testCase, string(output.NegativeEligibilityMode), "role_only");
    verifyEqual(testCase, output.NegativePositiveRatio, 2);
    verifyEqual(testCase, string(output.NegativeSamplingStrategy), ...
        "uniform_without_replacement");
    verifyEqual(testCase, string(output.NegativeTopupPolicy), ...
        "uniform_remaining_nonlinks");
    verifyEqual(testCase, string(output.TrophicLevelProtocol), "validated_v2");
    verifyEqual(testCase, string(output.TrophicSnapshotFile), "/tmp/example_snapshot.mat");
    verifyEqual(testCase, string(output.PseudoTrophicV2FailureReason), "ok");
    verifyEqual(testCase, output.PseudoTrophicV2LegacyMean, 2.5);
    verifyEqual(testCase, output.RandomTopupCount, 12);
    verifyEqual(testCase, output.TopupProportion, 0.30, 'AbsTol', 1e-12);
    verifyEqual(testCase, output.Properties.VariableNames(end-19:end), normalized_cols);
    verifyEqual(testCase, output{1, normalized_cols}, normalized_values, 'AbsTol', 1e-12);
end

function testObservedZeroProvenanceColumnsAreWritten(testCase)
    output_dir = tempname;
    mkdir(output_dir);
    cleanup = onCleanup(@() rmdir(output_dir, 's')); %#ok<NASGU>
    log_file = fullfile(output_dir, 'observed_zero.csv');

    init_log_file(log_file, false, false, 'WLNM_dir_neg');
    result = struct( ...
        'Version', 'WLNM_dir_neg', ...
        'TrainRatio', 0.60, ...
        'ExperimentID', 1, ...
        'Seed', 12345, ...
        'NegativeEligibilityMode', 'observed_zero', ...
        'NegativePositiveRatio', 2, ...
        'NegativeSamplingStrategy', 'uniform_without_replacement', ...
        'NegativeTopupPolicy', 'error', ...
        'CandidatePairCount', 831, ...
        'ObservedZeroPoolSize', 120, ...
        'RequestedNegativeCount', 80, ...
        'SelectedNegativeCount', 80, ...
        'RandomTopupCount', 0, ...
        'DataRegime', 'original_observed', ...
        'SpatialFold', 4, ...
        'GroupID', 'SG030', ...
        'Year', 2013, ...
        'InputPositiveCount', 40, ...
        'InputObservedZeroCount', 120, ...
        'InputUnresolvedCount', 671, ...
        'InputCandidateCount', 831, ...
        'OriginalStatus1Count', 40, ...
        'OriginalStatus0Count', 120, ...
        'OriginalStatusNACount', 671, ...
        'FinalStatus1Count', 55, ...
        'FinalStatus0Count', 200, ...
        'FinalStatusNACount', 576, ...
        'RequiredNegativeEligibilityMode', 'observed_zero', ...
        'SourceEvidenceSHA256', repmat('a', 1, 64), ...
        'SourceEvidencePath', 'fold_4/SG030/2013/edge_evidence.csv.gz', ...
        'PositiveSplitHash', repmat('b', 1, 64), ...
        'UniquePositiveSplitCount', 100, ...
        'TestPositiveBothEndpointsVisible', 12, ...
        'TestPositiveOneEndpointVisible', 4, ...
        'TestPositiveNeitherEndpointVisible', 0);
    append_results(log_file, result, false);

    output = readtable(log_file, 'VariableNamingRule', 'preserve');
    verifyEqual(testCase, string(output.NegativeEligibilityMode), "observed_zero");
    verifyEqual(testCase, string(output.NegativeTopupPolicy), "error");
    verifyEqual(testCase, output.CandidatePairCount, 831);
    verifyEqual(testCase, output.RandomTopupCount, 0);
    verifyEqual(testCase, string(output.DataRegime), "original_observed");
    verifyEqual(testCase, output.SpatialFold, 4);
    verifyEqual(testCase, string(output.GroupID), "SG030");
    verifyEqual(testCase, output.InputUnresolvedCount, 671);
    verifyEqual(testCase, output.OriginalStatusNACount, 671);
    verifyEqual(testCase, output.FinalStatus1Count, 55);
    verifyEqual(testCase, string(output.RequiredNegativeEligibilityMode), "observed_zero");
    verifyEqual(testCase, strlength(string(output.PositiveSplitHash)), 64);
    verifyEqual(testCase, output.UniquePositiveSplitCount, 100);
    verifyEqual(testCase, output.TestPositiveOneEndpointVisible, 4);
end

function testNormalizedColumnsAreAbsentFromOriginal(testCase)
    output_dir = tempname;
    mkdir(output_dir);
    cleanup = onCleanup(@() rmdir(output_dir, 's')); %#ok<NASGU>
    log_file = fullfile(output_dir, 'original.csv');

    init_log_file(log_file, false, false, 'WLNM_original');
    output = readtable(log_file, 'VariableNamingRule', 'preserve');

    verifyFalse(testCase, any(ismember( ...
        expected_normalized_gv_columns(), output.Properties.VariableNames)));
end

function testOldStandardLogSchemaIsRejectedWithoutRewrite(testCase)
    output_dir = tempname;
    mkdir(output_dir);
    cleanup = onCleanup(@() rmdir(output_dir, 's')); %#ok<NASGU>
    log_file = fullfile(output_dir, 'old_standard.csv');

    fid = fopen(log_file, 'w');
    assert(fid ~= -1, 'Could not create test log.');
    fprintf(fid, 'Iteration,Version\n');
    fclose(fid);

    verifyError(testCase, ...
        @() init_log_file(log_file, false, false, 'WLNM_dir_neg'), ...
        'init_log_file:WLNMDirNegSchemaMismatch');

    fid = fopen(log_file, 'r');
    assert(fid ~= -1, 'Could not reopen test log.');
    cleanup_fid = onCleanup(@() fclose(fid)); %#ok<NASGU>
    verifyEqual(testCase, fgetl(fid), 'Iteration,Version');
end

function cols = expected_normalized_gv_columns()
    prefixes = {'Empirical', 'Train', 'Pseudo', 'Delta'};
    suffixes = { ...
        'LinkageDensity', ...
        'MeanNormalizedGeneralityConsumersOnly', ...
        'MeanNormalizedVulnerabilityResourcesOnly', ...
        'NormalizedGeneralityStdAllSpecies', ...
        'NormalizedVulnerabilityStdAllSpecies' ...
    };

    cols = cell(1, numel(prefixes) * numel(suffixes));
    k = 0;
    for i = 1:numel(prefixes)
        for j = 1:numel(suffixes)
            k = k + 1;
            cols{k} = [prefixes{i} suffixes{j}];
        end
    end
end
