function tests = test_wlnm_dir_neg_observed_zero_guard
%TEST_WLNM_DIR_NEG_OBSERVED_ZERO_GUARD Prevent role-only use of Yujie MATs.
    tests = functiontests(localfunctions);
end

function testInputRequirementRejectsAccidentalRoleOnly(testCase)
    data = struct( ...
        'dataname', 'F01_SG009_2006', ...
        'net', sparse(1, 2, 1, 3, 3), ...
        'taxonomy', {{'a'; 'b'; 'c'}}, ...
        'mass', NaN(3, 1), ...
        'role', {{'resource'; 'consumer'; 'isolate'}}, ...
        'input_metadata', struct( ...
            'RequiredNegativeEligibilityMode', 'observed_zero'));

    config = minimal_config();
    config.negativeEligibilityMode = 'role_only';

    verifyError(testCase, ...
        @() run_wlnm_dir_neg(data, 10, 0.60, config), ...
        'run_wlnm_dir_neg:NegativeEligibilityModeMismatch');
end

function config = minimal_config()
    config = struct( ...
        'useParallel', false, ...
        'use_backbone', false, ...
        'inverse_backbone', false, ...
        'sweepBackboneTrain', false, ...
        'BackboneRatio', 0.5, ...
        'backboneRatioRange', 0.5, ...
        'numExperiments', 1, ...
        'nodeSelection', 'random', ...
        'checkConnectivity', false, ...
        'adaptiveConnectivity', false, ...
        'cvSaveConfusion', false, ...
        'evaluate_on_all_unseen', false, ...
        'exportBackboneCSV', false, ...
        'thresholdSweepEnabled', false, ...
        'thresholdSweepRange', 0.10:0.10:0.90, ...
        'negativeEligibilityMode', 'observed_zero', ...
        'negativePositiveRatio', 2, ...
        'negativeSamplingStrategy', 'uniform_without_replacement', ...
        'negativeTopupPolicy', 'error');
end
