function tests = test_wlnm_dir_neg_protocol_logging
%TEST_WLNM_DIR_NEG_PROTOCOL_LOGGING Verify sampler metadata reaches the CSV.
    tests = functiontests(localfunctions);
end

function testRoleOnlyProtocolColumnsAreWritten(testCase)
    output_dir = tempname;
    mkdir(output_dir);
    cleanup = onCleanup(@() rmdir(output_dir, 's')); %#ok<NASGU>
    log_file = fullfile(output_dir, 'role_only.csv');

    init_log_file(log_file, false, false, 'WLNM_dir_neg');

    result = struct( ...
        'Version', 'WLNM_dir_neg', ...
        'TrainRatio', 0.60, ...
        'ExperimentID', 1, ...
        'Seed', 123, ...
        'ThresholdMode', 'fixed', ...
        'Threshold', 0.50, ...
        'NegativeEligibilityMode', 'role_only', ...
        'NegativePositiveRatio', 2, ...
        'NegativeSamplingStrategy', 'uniform_without_replacement', ...
        'NegativeTopupPolicy', 'uniform_remaining_nonlinks', ...
        'RolePoolSize', 28, ...
        'MassPoolSize', 0, ...
        'EligiblePoolSize', 28, ...
        'FullNegativePoolSize', 90, ...
        'RequestedNegativeCount', 40, ...
        'SelectedNegativeCount', 40, ...
        'EligibleNegativeCount', 28, ...
        'EligibleShortfall', 12, ...
        'FullPoolShortfall', 0, ...
        'RandomTopupCount', 12, ...
        'TopupProportion', 0.30, ...
        'TrainNegativeCount', 24, ...
        'TestNegativeCount', 16 ...
    );
    append_results(log_file, result, false);

    output = readtable(log_file, 'VariableNamingRule', 'preserve');
    verifyEqual(testCase, height(output), 1);
    verifyEqual(testCase, string(output.NegativeEligibilityMode), "role_only");
    verifyEqual(testCase, output.NegativePositiveRatio, 2);
    verifyEqual(testCase, string(output.NegativeSamplingStrategy), ...
        "uniform_without_replacement");
    verifyEqual(testCase, string(output.NegativeTopupPolicy), ...
        "uniform_remaining_nonlinks");
    verifyEqual(testCase, output.RandomTopupCount, 12);
    verifyEqual(testCase, output.TopupProportion, 0.30, 'AbsTol', 1e-12);
end
