function init_log_file(log_file, use_backbone, inverse_backbone, version)
%INIT_LOG_FILE Create CSV header if missing.
%
% IMPORTANT:
% Existing log files are never overwritten. Standard WLNM_dir_neg logs are
% also checked for the current normalized generality/vulnerability schema
% so new fields cannot be silently dropped by the header-driven writer.

    if nargin < 2
        use_backbone = false;
    end
    if nargin < 3
        inverse_backbone = false;
    end
    if nargin < 4
        version = '';
    end

    if isfile(log_file)
        validate_existing_wlnm_dir_neg_schema(log_file, version);
        return;
    end

    fid = fopen(log_file, 'w');
    assert(fid ~= -1, 'Cannot open %s for writing.', log_file);
    c = onCleanup(@() fclose(fid));

    header = build_header(use_backbone, inverse_backbone, version);
    fprintf(fid, '%s\n', strjoin(header, ','));
end

% ============================================================
% Header builder
% ============================================================
function header = build_header(use_backbone, inverse_backbone, version)

    if use_backbone
        first_col = 'ExpID';
        if inverse_backbone
            ratio_col = 'NonBackboneRatio';
        else
            ratio_col = 'BackboneRatio';
        end
    else
        first_col = 'Iteration';
        ratio_col = '';
    end

    base_cols = { ...
        first_col, ...
        'Version', ...
        'ROC_AUC', 'PR_AUC', 'TimeElapsed', 'K', 'TrainRatio', ...
        'ExperimentID', 'Seed', 'ThresholdMode', 'TrophicLevelProtocol', ...
        'TrophicSnapshotFile' ...
    };

    if any(strcmpi(strtrim(char(string(version))), {'WLNM_dir_neg', 'WLNM_dir_neg_kfold'}))
        negative_sampling_cols = { ...
            'NegativeEligibilityMode', ...
            'NegativePositiveRatio', ...
            'NegativeSamplingStrategy', ...
            'NegativeTopupPolicy', ...
            'RolePoolSize', ...
            'MassPoolSize', ...
            'EligiblePoolSize', ...
            'FullNegativePoolSize', ...
            'RequestedNegativeCount', ...
            'SelectedNegativeCount', ...
            'EligibleNegativeCount', ...
            'EligibleShortfall', ...
            'FullPoolShortfall', ...
            'RandomTopupCount', ...
            'TopupProportion', ...
            'TrainNegativeCount', ...
            'TestNegativeCount', ...
            'CandidatePairCount', ...
            'ObservedZeroPoolSize', ...
            'TrainNegativeBothEndpointsVisible', ...
            'TrainNegativeOneEndpointVisible', ...
            'TrainNegativeNeitherEndpointVisible', ...
            'TestNegativeBothEndpointsVisible', ...
            'TestNegativeOneEndpointVisible', ...
            'TestNegativeNeitherEndpointVisible', ...
            'TestPositiveBothEndpointsVisible', ...
            'TestPositiveOneEndpointVisible', ...
            'TestPositiveNeitherEndpointVisible', ...
            'TrainTestNegativeOverlapCount', ...
            'PositiveTrainTestOverlapCount', ...
            'DataRegime', ...
            'SpatialFold', ...
            'GroupID', ...
            'Year', ...
            'InputPositiveCount', ...
            'InputObservedZeroCount', ...
            'InputUnresolvedCount', ...
            'InputCandidateCount', ...
            'OriginalStatus1Count', ...
            'OriginalStatus0Count', ...
            'OriginalStatusNACount', ...
            'FinalStatus1Count', ...
            'FinalStatus0Count', ...
            'FinalStatusNACount', ...
            'RequiredNegativeEligibilityMode', ...
            'SourceEvidenceSHA256', ...
            'SourceEvidencePath', ...
            'PositiveSplitHash', ...
            'UniquePositiveSplitCount' ...
        };
        base_cols = [base_cols, negative_sampling_cols];
    end

    if use_backbone
        base_cols = [base_cols, {ratio_col}];
    end

    base_cols = [base_cols, { ...
        'Threshold', 'Precision', 'Recall', 'F1Score', ...
        'TestTP', 'TestFP', 'TestFN', 'TestTN', ...
        'TestTPR', 'TestTNR', 'TestFPR', 'TestFNR', ...
        'TestPrecision', 'TestRecall', 'TestF1Score', ...
        'TestAccuracy', 'TestExpectedAccuracy', 'TestKappa', ...
        'TestMCC', 'TestTSS', ...
        'TotalLinks', 'TrainLinks', 'TestLinks', ...
        'BackboneTotal', 'NonBackboneTotal', ...
        'BackboneTrainLinks', 'NonBackboneTrainLinks', ...
        'BackboneTestLinks', 'NonBackboneTestLinks' ...
    }];

    ecological_cols = [ ...
    { ...
        'EmpiricalNumSpecies', ...
        'EmpiricalLinks', ...
        'EmpiricalConnectance', ...
        'EmpiricalMeanTrophicLevel', ...
        'EmpiricalMeanDegree', ...
        'EmpiricalMeanGenerality', ...
        'EmpiricalMeanVulnerability' ...
    }, ...
    extended_structural_cols('Empirical'), ...
    networkx_trophic_diagnostic_cols('Empirical'), ...
    { ...
        'EmpiricalPropBasal', ...
        'EmpiricalPropIntermediate', ...
        'EmpiricalPropTop', ...
        'TrainNumSpecies', ...
        'TrainConnectance', ...
        'TrainMeanTrophicLevel', ...
        'TrainMeanDegree', ...
        'TrainMeanGenerality', ...
        'TrainMeanVulnerability' ...
    }, ...
    extended_structural_cols('Train'), ...
    networkx_trophic_diagnostic_cols('Train'), ...
    { ...
        'TrainPropBasal', ...
        'TrainPropIntermediate', ...
        'TrainPropTop', ...
        'PseudoNumSpecies', ...
        'PseudoLinks', ...
        'PseudoConnectance', ...
        'PseudoMeanTrophicLevel', ...
        'PseudoMeanDegree', ...
        'PseudoMeanGenerality', ...
        'PseudoMeanVulnerability' ...
    }, ...
    extended_structural_cols('Pseudo'), ...
    networkx_trophic_diagnostic_cols('Pseudo'), ...
    { ...
        'PseudoPropBasal', ...
        'PseudoPropIntermediate', ...
        'PseudoPropTop', ...
        'DeltaLinks', ...
        'DeltaConnectance', ...
        'DeltaMeanTrophicLevel', ...
        'DeltaMeanDegree', ...
        'DeltaMeanGenerality', ...
        'DeltaMeanVulnerability' ...
    }, ...
    extended_structural_cols('Delta'), ...
    { ...
        'DeltaPropBasal', ...
        'DeltaPropIntermediate', ...
        'DeltaPropTop', ...
        'PseudoTP', ...
        'PseudoFP', ...
        'PseudoFN', ...
        'PseudoTN', ...
        'PseudoTPR', ...
        'PseudoTNR', ...
        'PseudoFPR', ...
        'PseudoFNR', ...
        'PseudoPrecision', ...
        'PseudoRecall', ...
        'PseudoF1Score', ...
        'PseudoMCC', ...
        'PseudoTSS', ...
        'PseudoJaccardLinks', ...
        'NumPredictedNovelLinks', ...
        'NumTrueNovelLinks', ...
        'EvaluateOnAllUnseen' ...
    }];

    trophic_v2_cols = [ ...
        trophic_v2_diagnostic_cols('Empirical'), ...
        trophic_v2_diagnostic_cols('Train'), ...
        trophic_v2_diagnostic_cols('Pseudo') ...
    ];

    cv_cols = {'CvK', 'FoldID', 'NumFolds'};

    header = [base_cols, ecological_cols, trophic_v2_cols, cv_cols];
    if is_standard_wlnm_dir_neg(version)
        % Append-only: preserve every existing column name and position.
        header = [header, normalized_gv_cols()];
    end
end

function validate_existing_wlnm_dir_neg_schema(log_file, version)
    if ~is_standard_wlnm_dir_neg(version)
        return;
    end

    fid = fopen(log_file, 'r');
    assert(fid ~= -1, 'Cannot open %s for reading.', log_file);
    c = onCleanup(@() fclose(fid));
    header_line = fgetl(fid);

    if ischar(header_line)
        existing_cols = strsplit(strtrim(header_line), ',');
    else
        existing_cols = {};
    end

    required_cols = normalized_gv_cols();
    missing_cols = setdiff(required_cols, existing_cols, 'stable');
    if ~isempty(missing_cols)
        error('init_log_file:WLNMDirNegSchemaMismatch', ...
            ['Existing WLNM_dir_neg log uses an older schema and is missing: %s. ' ...
             'Use a fresh result directory or log file; the existing CSV was not modified.'], ...
            strjoin(missing_cols, ', '));
    end
end

function tf = is_standard_wlnm_dir_neg(version)
    tf = strcmpi(strtrim(char(string(version))), 'WLNM_dir_neg');
end

function cols = normalized_gv_cols()
    prefixes = {'Empirical', 'Train', 'Pseudo', 'Delta'};
    suffixes = { ...
        'LinkageDensity', ...
        'MeanNormalizedGeneralityConsumersOnly', ...
        'MeanNormalizedVulnerabilityResourcesOnly', ...
        'NormalizedGeneralityStdAllSpecies', ...
        'NormalizedVulnerabilityStdAllSpecies' ...
    };

    cols = cell(1, numel(prefixes) * numel(suffixes));
    k = 0;
    for i = 1:numel(prefixes)
        for j = 1:numel(suffixes)
            k = k + 1;
            cols{k} = [prefixes{i} suffixes{j}];
        end
    end
end

function cols = trophic_v2_diagnostic_cols(prefix)
    suffixes = { ...
        'NumSpeciesFull', 'NumSpeciesLargest', 'NumSpeciesWithLevel', ...
        'LargestFraction', 'StatusCode', 'NumBasal', 'NumUnreachable', ...
        'ReciprocalCondition', 'ScaledResidual', 'ResidualNorm', ...
        'CandidateMin', 'CandidateMax', 'AboveLegacyCap', ...
        'PrecisionDigits', 'PrecisionRelativeDifference', 'SolverCode', ...
        'FailureReason', 'LegacyMean', 'LegacyStatusCode' ...
    };
    cols = cellfun(@(suffix) [prefix 'TrophicV2' suffix], suffixes, ...
        'UniformOutput', false);
end

function cols = extended_structural_cols(prefix)
    suffixes = { ...
        'DegreeStd', ...
        'DegreeCV', ...
        'DegreeGini', ...
        'GeneralityStd', ...
        'GeneralityCV', ...
        'GeneralityGini', ...
        'VulnerabilityStd', ...
        'VulnerabilityCV', ...
        'VulnerabilityGini', ...
        'TrophicLevelStd', ...
        'TrophicLevelCV', ...
        'TrophicLevelRange', ...
        'NetworkXMeanTrophicLevel', ...
        'NetworkXTrophicLevelStd', ...
        'NetworkXTrophicLevelRange', ...
        'MeanLocalClustering', ...
        'Transitivity', ...
        'NumTriangles', ...
        'TriangleDensity', ...
        'MeanDietOverlap' ...
    };

    cols = strcat(prefix, suffixes);
end

function cols = networkx_trophic_diagnostic_cols(prefix)
    suffixes = { ...
        'NetworkXTrophicLevelNumSpeciesFull', ...
        'NetworkXTrophicLevelNumSpeciesLargest', ...
        'NetworkXTrophicLevelNumSpeciesWithLevel', ...
        'NetworkXTrophicLevelLargestFraction', ...
        'NetworkXTrophicLevelStatusCode' ...
    };

    cols = strcat(prefix, suffixes);
end
