function init_log_file(log_file, use_backbone, inverse_backbone)
%INIT_LOG_FILE Create CSV header if missing.
%
% IMPORTANT:
% If an old log file already exists with a previous header schema, this
% function will NOT overwrite it. Use a fresh log directory or delete the
% old CSV first.

    if nargin < 2
        use_backbone = false;
    end
    if nargin < 3
        inverse_backbone = false;
    end

    if ~isfile(log_file)
        fid = fopen(log_file, 'w');
        assert(fid ~= -1, 'Cannot open %s for writing.', log_file);
        c = onCleanup(@() fclose(fid));

        header = build_header(use_backbone, inverse_backbone);
        fprintf(fid, '%s\n', strjoin(header, ','));
    end
end

% ============================================================
% Header builder
% ============================================================
function header = build_header(use_backbone, inverse_backbone)

    if use_backbone
        first_col = 'ExpID';
        if inverse_backbone
            ratio_col = 'NonBackboneRatio';
        else
            ratio_col = 'BackboneRatio';
        end
    else
        first_col = 'Iteration';
        ratio_col = '';
    end

    base_cols = { ...
        first_col, ...
        'Version', ...
        'ROC_AUC', 'PR_AUC', 'TimeElapsed', 'K', 'TrainRatio', ...
        'ExperimentID', 'Seed', 'ThresholdMode' ...
    };

    if use_backbone
        base_cols = [base_cols, {ratio_col}];
    end

    base_cols = [base_cols, { ...
        'Threshold', 'Precision', 'Recall', 'F1Score', ...
        'TestTP', 'TestFP', 'TestFN', 'TestTN', ...
        'TestTPR', 'TestTNR', 'TestFPR', 'TestFNR', ...
        'TestPrecision', 'TestRecall', 'TestF1Score', ...
        'TestAccuracy', 'TestExpectedAccuracy', 'TestKappa', ...
        'TestMCC', 'TestTSS', ...
        'TotalLinks', 'TrainLinks', 'TestLinks', ...
        'BackboneTotal', 'NonBackboneTotal', ...
        'BackboneTrainLinks', 'NonBackboneTrainLinks', ...
        'BackboneTestLinks', 'NonBackboneTestLinks' ...
    }];

    ecological_cols = [ ...
    { ...
        'EmpiricalNumSpecies', ...
        'EmpiricalLinks', ...
        'EmpiricalConnectance', ...
        'EmpiricalMeanTrophicLevel', ...
        'EmpiricalMeanDegree', ...
        'EmpiricalMeanGenerality', ...
        'EmpiricalMeanVulnerability' ...
    }, ...
    extended_structural_cols('Empirical'), ...
    networkx_trophic_diagnostic_cols('Empirical'), ...
    { ...
        'EmpiricalPropBasal', ...
        'EmpiricalPropIntermediate', ...
        'EmpiricalPropTop', ...
        'PseudoNumSpecies', ...
        'PseudoLinks', ...
        'PseudoConnectance', ...
        'PseudoMeanTrophicLevel', ...
        'PseudoMeanDegree', ...
        'PseudoMeanGenerality', ...
        'PseudoMeanVulnerability' ...
    }, ...
    extended_structural_cols('Pseudo'), ...
    networkx_trophic_diagnostic_cols('Pseudo'), ...
    { ...
        'PseudoPropBasal', ...
        'PseudoPropIntermediate', ...
        'PseudoPropTop', ...
        'DeltaLinks', ...
        'DeltaConnectance', ...
        'DeltaMeanTrophicLevel', ...
        'DeltaMeanDegree', ...
        'DeltaMeanGenerality', ...
        'DeltaMeanVulnerability' ...
    }, ...
    extended_structural_cols('Delta'), ...
    { ...
        'DeltaPropBasal', ...
        'DeltaPropIntermediate', ...
        'DeltaPropTop', ...
        'PseudoTP', ...
        'PseudoFP', ...
        'PseudoFN', ...
        'PseudoTN', ...
        'PseudoTPR', ...
        'PseudoTNR', ...
        'PseudoFPR', ...
        'PseudoFNR', ...
        'PseudoPrecision', ...
        'PseudoRecall', ...
        'PseudoF1Score', ...
        'PseudoMCC', ...
        'PseudoTSS', ...
        'PseudoJaccardLinks', ...
        'NumPredictedNovelLinks', ...
        'NumTrueNovelLinks', ...
        'EvaluateOnAllUnseen' ...
    }];

    cv_cols = {'CvK', 'FoldID', 'NumFolds'};

    header = [base_cols, ecological_cols, cv_cols];
end

function cols = extended_structural_cols(prefix)
    suffixes = { ...
        'DegreeStd', ...
        'DegreeCV', ...
        'DegreeGini', ...
        'GeneralityStd', ...
        'GeneralityCV', ...
        'GeneralityGini', ...
        'VulnerabilityStd', ...
        'VulnerabilityCV', ...
        'VulnerabilityGini', ...
        'TrophicLevelStd', ...
        'TrophicLevelCV', ...
        'TrophicLevelRange', ...
        'NetworkXMeanTrophicLevel', ...
        'NetworkXTrophicLevelStd', ...
        'NetworkXTrophicLevelRange', ...
        'MeanLocalClustering', ...
        'Transitivity', ...
        'NumTriangles', ...
        'TriangleDensity', ...
        'MeanDietOverlap' ...
    };

    cols = strcat(prefix, suffixes);
end

function cols = networkx_trophic_diagnostic_cols(prefix)
    suffixes = { ...
        'NetworkXTrophicLevelNumSpeciesFull', ...
        'NetworkXTrophicLevelNumSpeciesLargest', ...
        'NetworkXTrophicLevelNumSpeciesWithLevel', ...
        'NetworkXTrophicLevelLargestFraction', ...
        'NetworkXTrophicLevelStatusCode' ...
    };

    cols = strcat(prefix, suffixes);
end
