function results = run_wlnm_dir_neg(data, K, ratioTrain, config)
%RUN_WLNM_DIR_NEG Runner for WLNM with directed + negative sampling.

    % ---- Minimal required config fields (controlled from Main) ----
    required_fields = { ...
        'useParallel', ...
        'use_backbone', ...
        'inverse_backbone', ...
        'sweepBackboneTrain', ...
        'BackboneRatio', ...
        'backboneRatioRange', ...
        'numExperiments', ...
        'nodeSelection', ...
        'cvSaveConfusion', ...
        'evaluate_on_all_unseen', ...
        'exportBackboneCSV' ...
    };

    for kf = 1:numel(required_fields)
        f = required_fields{kf};
        if ~isfield(config, f)
            error('[run_wlnm_dir_neg] Missing required config field: %s. Define it in Main.m.', f);
        end
    end

    % ---- Backbone usage comes ONLY from Main ----
    has_mask = isfield(data, 'backbone_mask') && ~isempty(data.backbone_mask);

    use_backbone = logical(config.use_backbone) && has_mask;

    if config.use_backbone && ~has_mask
        warning(['[run_wlnm_dir_neg] config.use_backbone=true but data.backbone_mask is empty. ' ...
                 'Falling back to standard split. Backbone must be computed in Main.m.']);
    end

    if config.inverse_backbone && ~use_backbone
        warning(['[run_wlnm_dir_neg] inverse_backbone=true but no backbone_mask was provided. ' ...
                 'Inverse backbone mode will be ignored for this dataset.']);
    end

    % ---- Backbone ratio list ----
    if use_backbone
        if config.sweepBackboneTrain
            rb_list = config.backboneRatioRange;
        else
            rb_list = config.BackboneRatio;
        end
        rb_list = rb_list(:)';   % row vector
    else
        rb_list = 0;
    end

    % ---- Preallocate results ----
    R = numel(rb_list) * config.numExperiments;
    results = repmat(make_result_template(K, ratioTrain, 0, empty_split_stats()), R, 1);

    % ---- Locals ----
    dataname      = data.dataname;
    net           = data.net;
    taxonomy      = data.taxonomy;
    mass          = data.mass;
    role          = data.role;
    nodeSelection = config.nodeSelection;

    backbone_mask = [];
    if has_mask
        backbone_mask = data.backbone_mask;
    end

    % ---- Confusion / export control ----
    save_confusion_flag = logical(config.cvSaveConfusion);
    export_backbone_flag = logical(config.exportBackboneCSV);

    row = 0;

    for rb = rb_list
        % ------------------------------------------------------------
        % Backbone mask: ONLY use precomputed one from Main
        % ------------------------------------------------------------
        if use_backbone
            bb_mask = backbone_mask;
        else
            bb_mask = [];
        end

        % ------------------------------------------------------------
        % Obtain train/test split
        % ------------------------------------------------------------
        if use_backbone
            fprintf('[SweepBackbone] ratioTrain=%.2f | BackboneRatio=%.2f | inverse_backbone=%d\n', ...
                ratioTrain, rb, config.inverse_backbone);

            args = { ...
                'use_backbone',      true, ...
                'ratioBackbone',     rb, ...
                'inverse_backbone',  config.inverse_backbone, ...
                'backbone_mask',     bb_mask ...
            };

            [train, test, split_stats] = DivideNet_dir_neg(net, ratioTrain, false, false, args{:});
        else
            [train, test, split_stats] = DivideNet_dir_neg(net, ratioTrain, false, false);
        end

        % ------------------------------------------------------------
        % WLNM experiments
        % ------------------------------------------------------------
        if config.useParallel
            res_block = repmat(make_result_template(K, ratioTrain, rb, split_stats), config.numExperiments, 1);

            start_idx = 1;
            if save_confusion_flag
                t0 = tic;
                [roc_auc, pr_auc, thr, prec, rec, f1, aux] = WLNM_dir_neg( ...
                    dataname, train, test, K, taxonomy, mass, role, nodeSelection, ratioTrain, ...
                    'save_confusion', true, ...
                    'backbone_mask', bb_mask, ...
                    'export_backbone', (use_backbone && export_backbone_flag), ...
                    'evaluate_on_all_unseen', config.evaluate_on_all_unseen);

                res_block(1) = populate_result_row( ...
                    res_block(1), roc_auc, pr_auc, thr, prec, rec, f1, toc(t0), aux);

                start_idx = 2;
            end

            if start_idx <= config.numExperiments
                parfor i = start_idx:config.numExperiments
                    t0 = tic;

                    [roc_auc, pr_auc, thr, prec, rec, f1, aux] = WLNM_dir_neg( ...
                        dataname, train, test, K, taxonomy, mass, role, nodeSelection, ratioTrain, ...
                        'save_confusion', false, ...
                        'backbone_mask', bb_mask, ...
                        'export_backbone', false, ...
                        'evaluate_on_all_unseen', config.evaluate_on_all_unseen);

                    local_res = make_result_template(K, ratioTrain, rb, split_stats);
                    local_res = populate_result_row( ...
                        local_res, roc_auc, pr_auc, thr, prec, rec, f1, toc(t0), aux);

                    res_block(i) = local_res;
                end
            end

            for i = 1:config.numExperiments
                row = row + 1;
                results(row) = res_block(i);
            end

        else
            for i = 1:config.numExperiments
                do_export = save_confusion_flag && (i == 1);

                t0 = tic;
                [roc_auc, pr_auc, thr, prec, rec, f1, aux] = WLNM_dir_neg( ...
                    dataname, train, test, K, taxonomy, mass, role, nodeSelection, ratioTrain, ...
                    'save_confusion', do_export, ...
                    'backbone_mask', bb_mask, ...
                    'export_backbone', (do_export && use_backbone && export_backbone_flag), ...
                    'evaluate_on_all_unseen', config.evaluate_on_all_unseen);

                row = row + 1;

                results(row) = make_result_template(K, ratioTrain, rb, split_stats);
                results(row) = populate_result_row( ...
                    results(row), roc_auc, pr_auc, thr, prec, rec, f1, toc(t0), aux);
            end
        end
    end
end

% ============================================================
% Result row template
% ============================================================
function out = make_result_template(K, ratioTrain, rb, split_stats)
    out = struct( ...
        'ROC_AUC',0, 'PR_AUC',0, 'TimeElapsed','', ...
        'K',K, 'TrainRatio',ratioTrain, 'BackboneRatio',rb, ...
        'Threshold',0, 'Precision',0, 'Recall',0, 'F1Score',0, ...
        'TotalLinks',split_stats.TotalLinks, ...
        'TrainLinks',split_stats.TrainLinks, ...
        'TestLinks',split_stats.TestLinks, ...
        'BackboneTotal',split_stats.BackboneTotal, ...
        'NonBackboneTotal',split_stats.NonBackboneTotal, ...
        'BackboneTrainLinks',split_stats.BackboneTrainLinks, ...
        'NonBackboneTrainLinks',split_stats.NonBackboneTrainLinks, ...
        'BackboneTestLinks',split_stats.BackboneTestLinks, ...
        'NonBackboneTestLinks',split_stats.NonBackboneTestLinks, ...
        'EmpiricalNumSpecies',NaN, ...
        'EmpiricalLinks',NaN, ...
        'EmpiricalConnectance',NaN, ...
        'EmpiricalMeanTrophicLevel',NaN, ...
        'EmpiricalMeanDegree',NaN, ...
        'EmpiricalMeanGenerality',NaN, ...
        'EmpiricalMeanVulnerability',NaN, ...
        'EmpiricalPropBasal',NaN, ...
        'EmpiricalPropIntermediate',NaN, ...
        'EmpiricalPropTop',NaN, ...
        'PseudoNumSpecies',NaN, ...
        'PseudoLinks',NaN, ...
        'PseudoConnectance',NaN, ...
        'PseudoMeanTrophicLevel',NaN, ...
        'PseudoMeanDegree',NaN, ...
        'PseudoMeanGenerality',NaN, ...
        'PseudoMeanVulnerability',NaN, ...
        'PseudoPropBasal',NaN, ...
        'PseudoPropIntermediate',NaN, ...
        'PseudoPropTop',NaN, ...
        'DeltaLinks',NaN, ...
        'DeltaConnectance',NaN, ...
        'DeltaMeanTrophicLevel',NaN, ...
        'DeltaMeanDegree',NaN, ...
        'DeltaMeanGenerality',NaN, ...
        'DeltaMeanVulnerability',NaN, ...
        'DeltaPropBasal',NaN, ...
        'DeltaPropIntermediate',NaN, ...
        'DeltaPropTop',NaN, ...
        'PseudoTP',NaN, ...
        'PseudoFP',NaN, ...
        'PseudoFN',NaN, ...
        'PseudoTN',NaN, ...
        'PseudoTPR',NaN, ...
        'PseudoTNR',NaN, ...
        'PseudoFPR',NaN, ...
        'PseudoFNR',NaN, ...
        'PseudoPrecision',NaN, ...
        'PseudoRecall',NaN, ...
        'PseudoF1Score',NaN, ...
        'PseudoTSS',NaN, ...
        'PseudoJaccardLinks',NaN, ...
        'NumPredictedNovelLinks',NaN, ...
        'NumTrueNovelLinks',NaN, ...
        'EvaluateOnAllUnseen',NaN ...
    );
end

% ============================================================
% Empty split stats template
% ============================================================
function st = empty_split_stats()
    st = struct( ...
        'TotalLinks',0, ...
        'TrainLinks',0, ...
        'TestLinks',0, ...
        'BackboneTotal',0, ...
        'NonBackboneTotal',0, ...
        'BackboneTrainLinks',0, ...
        'NonBackboneTrainLinks',0, ...
        'BackboneTestLinks',0, ...
        'NonBackboneTestLinks',0 ...
    );
end

% ============================================================
% Fill predictive + ecological metrics into result row
% ============================================================
function out = populate_result_row(out, roc_auc, pr_auc, thr, prec, rec, f1, elapsed_seconds, aux)

    out.ROC_AUC     = roc_auc;
    out.PR_AUC      = pr_auc;
    out.TimeElapsed = datestr(seconds(elapsed_seconds), 'HH:MM:SS');
    out.Threshold   = thr;
    out.Precision   = prec;
    out.Recall      = rec;
    out.F1Score     = f1;

    flat = flatten_aux_metrics(aux);
    fn = fieldnames(flat);
    for k = 1:numel(fn)
        out.(fn{k}) = flat.(fn{k});
    end
end

% ============================================================
% Flatten aux struct from WLNM_dir_neg into scalar fields
% ============================================================
function flat = flatten_aux_metrics(aux)

    flat = struct( ...
        'EmpiricalNumSpecies',NaN, ...
        'EmpiricalLinks',NaN, ...
        'EmpiricalConnectance',NaN, ...
        'EmpiricalMeanTrophicLevel',NaN, ...
        'EmpiricalMeanDegree',NaN, ...
        'EmpiricalMeanGenerality',NaN, ...
        'EmpiricalMeanVulnerability',NaN, ...
        'EmpiricalPropBasal',NaN, ...
        'EmpiricalPropIntermediate',NaN, ...
        'EmpiricalPropTop',NaN, ...
        'PseudoNumSpecies',NaN, ...
        'PseudoLinks',NaN, ...
        'PseudoConnectance',NaN, ...
        'PseudoMeanTrophicLevel',NaN, ...
        'PseudoMeanDegree',NaN, ...
        'PseudoMeanGenerality',NaN, ...
        'PseudoMeanVulnerability',NaN, ...
        'PseudoPropBasal',NaN, ...
        'PseudoPropIntermediate',NaN, ...
        'PseudoPropTop',NaN, ...
        'DeltaLinks',NaN, ...
        'DeltaConnectance',NaN, ...
        'DeltaMeanTrophicLevel',NaN, ...
        'DeltaMeanDegree',NaN, ...
        'DeltaMeanGenerality',NaN, ...
        'DeltaMeanVulnerability',NaN, ...
        'DeltaPropBasal',NaN, ...
        'DeltaPropIntermediate',NaN, ...
        'DeltaPropTop',NaN, ...
        'PseudoTP',NaN, ...
        'PseudoFP',NaN, ...
        'PseudoFN',NaN, ...
        'PseudoTN',NaN, ...
        'PseudoTPR',NaN, ...
        'PseudoTNR',NaN, ...
        'PseudoFPR',NaN, ...
        'PseudoFNR',NaN, ...
        'PseudoPrecision',NaN, ...
        'PseudoRecall',NaN, ...
        'PseudoF1Score',NaN, ...
        'PseudoTSS',NaN, ...
        'PseudoJaccardLinks',NaN, ...
        'NumPredictedNovelLinks',NaN, ...
        'NumTrueNovelLinks',NaN, ...
        'EvaluateOnAllUnseen',NaN ...
    );

    if nargin == 0 || isempty(aux)
        return;
    end

    % ---- empirical metrics ----
    if isfield(aux, 'empirical_metrics') && ~isempty(aux.empirical_metrics)
        m = aux.empirical_metrics;
        flat.EmpiricalNumSpecies        = safe_field(m, 'NumSpecies');
        flat.EmpiricalLinks             = safe_field(m, 'NumLinks');
        flat.EmpiricalConnectance       = safe_field(m, 'Connectance');
        flat.EmpiricalMeanTrophicLevel  = safe_field(m, 'MeanTrophicLevel');
        flat.EmpiricalMeanDegree        = safe_field(m, 'MeanDegree');
        flat.EmpiricalMeanGenerality    = safe_field(m, 'MeanGenerality');
        flat.EmpiricalMeanVulnerability = safe_field(m, 'MeanVulnerability');
        flat.EmpiricalPropBasal         = safe_field(m, 'PropBasal');
        flat.EmpiricalPropIntermediate  = safe_field(m, 'PropIntermediate');
        flat.EmpiricalPropTop           = safe_field(m, 'PropTop');
    end

    % ---- pseudo metrics ----
    if isfield(aux, 'pseudo_metrics') && ~isempty(aux.pseudo_metrics)
        m = aux.pseudo_metrics;
        flat.PseudoNumSpecies        = safe_field(m, 'NumSpecies');
        flat.PseudoLinks             = safe_field(m, 'NumLinks');
        flat.PseudoConnectance       = safe_field(m, 'Connectance');
        flat.PseudoMeanTrophicLevel  = safe_field(m, 'MeanTrophicLevel');
        flat.PseudoMeanDegree        = safe_field(m, 'MeanDegree');
        flat.PseudoMeanGenerality    = safe_field(m, 'MeanGenerality');
        flat.PseudoMeanVulnerability = safe_field(m, 'MeanVulnerability');
        flat.PseudoPropBasal         = safe_field(m, 'PropBasal');
        flat.PseudoPropIntermediate  = safe_field(m, 'PropIntermediate');
        flat.PseudoPropTop           = safe_field(m, 'PropTop');
    end

    % ---- deltas ----
    flat.DeltaLinks             = flat.PseudoLinks            - flat.EmpiricalLinks;
    flat.DeltaConnectance       = flat.PseudoConnectance      - flat.EmpiricalConnectance;
    flat.DeltaMeanTrophicLevel  = flat.PseudoMeanTrophicLevel - flat.EmpiricalMeanTrophicLevel;
    flat.DeltaMeanDegree        = flat.PseudoMeanDegree       - flat.EmpiricalMeanDegree;
    flat.DeltaMeanGenerality    = flat.PseudoMeanGenerality   - flat.EmpiricalMeanGenerality;
    flat.DeltaMeanVulnerability = flat.PseudoMeanVulnerability- flat.EmpiricalMeanVulnerability;
    flat.DeltaPropBasal         = flat.PseudoPropBasal        - flat.EmpiricalPropBasal;
    flat.DeltaPropIntermediate  = flat.PseudoPropIntermediate - flat.EmpiricalPropIntermediate;
    flat.DeltaPropTop           = flat.PseudoPropTop          - flat.EmpiricalPropTop;

    % ---- comparison metrics ----
    if isfield(aux, 'comparison_metrics') && ~isempty(aux.comparison_metrics)
        c = aux.comparison_metrics;
        flat.PseudoTP           = safe_field(c, 'TP');
        flat.PseudoFP           = safe_field(c, 'FP');
        flat.PseudoFN           = safe_field(c, 'FN');
        flat.PseudoTN           = safe_field(c, 'TN');
        flat.PseudoTPR          = safe_field(c, 'TPR');
        flat.PseudoTNR          = safe_field(c, 'TNR');
        flat.PseudoFPR          = safe_field(c, 'FPR');
        flat.PseudoFNR          = safe_field(c, 'FNR');
        flat.PseudoPrecision    = safe_field(c, 'Precision');
        flat.PseudoRecall       = safe_field(c, 'Recall');
        flat.PseudoF1Score      = safe_field(c, 'F1Score');
        flat.PseudoTSS          = safe_field(c, 'TSS');
        flat.PseudoJaccardLinks = safe_field(c, 'JaccardLinks');
    end

    % ---- bookkeeping ----
    if isfield(aux, 'NumPredictedNovelLinks')
        flat.NumPredictedNovelLinks = aux.NumPredictedNovelLinks;
    end
    if isfield(aux, 'NumTrueNovelLinks')
        flat.NumTrueNovelLinks = aux.NumTrueNovelLinks;
    end
    if isfield(aux, 'EvaluateOnAllUnseen')
        flat.EvaluateOnAllUnseen = double(aux.EvaluateOnAllUnseen);
    end
end

% ============================================================
% Safe struct field access
% ============================================================
function val = safe_field(s, f)
    if isstruct(s) && isfield(s, f) && ~isempty(s.(f))
        val = s.(f);
    else
        val = NaN;
    end
end
