function results = run_wlnm_dir_neg(data, K, ratioTrain, config)
%RUN_WLNM_DIR_NEG Runner for WLNM with directed + negative sampling.

    % ---- Minimal required config fields (controlled from Main) ----
    required_fields = { ...
        'useParallel', ...
        'use_backbone', ...
        'inverse_backbone', ...
        'sweepBackboneTrain', ...
        'BackboneRatio', ...
        'backboneRatioRange', ...
        'numExperiments', ...
        'nodeSelection', ...
        'checkConnectivity', ...
        'adaptiveConnectivity', ...
        'cvSaveConfusion', ...
        'evaluate_on_all_unseen', ...
        'exportBackboneCSV' ...
    };

    for kf = 1:numel(required_fields)
        f = required_fields{kf};
        if ~isfield(config, f)
            error('[run_wlnm_dir_neg] Missing required config field: %s. Define it in Main.m.', f);
        end
    end

    % ---- Backbone usage comes ONLY from Main ----
    has_mask = isfield(data, 'backbone_mask') && ~isempty(data.backbone_mask);

    use_backbone = logical(config.use_backbone) && has_mask;

    if config.use_backbone && ~has_mask
        warning(['[run_wlnm_dir_neg] config.use_backbone=true but data.backbone_mask is empty. ' ...
                 'Falling back to standard split. Backbone must be computed in Main.m.']);
    end

    if config.inverse_backbone && ~use_backbone
        warning(['[run_wlnm_dir_neg] inverse_backbone=true but no backbone_mask was provided. ' ...
                 'Inverse backbone mode will be ignored for this dataset.']);
    end

    % ---- Backbone ratio list ----
    if use_backbone
        if config.sweepBackboneTrain
            rb_list = config.backboneRatioRange;
        else
            rb_list = config.BackboneRatio;
        end
        rb_list = rb_list(:)';   % row vector
    else
        rb_list = 0;
    end

    % ---- Locals ----
    dataname      = data.dataname;
    net           = data.net;
    taxonomy      = data.taxonomy;
    mass          = data.mass;
    role          = data.role;
    nodeSelection = config.nodeSelection;

    backbone_mask = [];
    if has_mask
        backbone_mask = data.backbone_mask;
    end

    % ---- Repetition / export control ----
    resample_splits = get_config_bool(config, 'resampleSplitsEachExperiment', true);
    base_seed = get_config_number(config, 'baseSeed', 12345);
    save_confusion_flag = get_config_bool(config, 'exportAuxiliaryCSVs', logical(config.cvSaveConfusion));
    export_backbone_flag = logical(config.exportBackboneCSV);
    artifact_dir = get_config_text(config, 'artifactDir', 'data/result/confusion_matrix_csv/');
    threshold_mode = get_config_text(config, 'thresholdMode', 'fixed');
    fixed_threshold = get_config_number(config, 'fixedThreshold', 0.5);
    version = get_config_text(config, 'version', 'WLNM_dir_neg');
    encode_parallel = get_config_bool(config, 'useGraphEncodingParallel', false) && ~logical(config.useParallel);
    compute_ecological_metrics = get_config_bool(config, 'computeEcologicalMetrics', true);

    % ---- Preallocate results ----
    R = numel(rb_list) * config.numExperiments;
    results = repmat(make_result_template(K, ratioTrain, 0, empty_split_stats(), config, 0, 0), R, 1);

    row = 0;

    for rb = rb_list
        % ------------------------------------------------------------
        % Backbone mask: ONLY use precomputed one from Main
        % ------------------------------------------------------------
        if use_backbone
            bb_mask = backbone_mask;
        else
            bb_mask = [];
        end

        shared_train = [];
        shared_test = [];
        shared_split_stats = [];
        if ~resample_splits
            split_seed = make_experiment_seed(base_seed, dataname, K, ratioTrain, rb, 0);
            rng(split_seed, 'twister');
            [shared_train, shared_test, shared_split_stats] = get_split( ...
                net, ratioTrain, rb, use_backbone, bb_mask, config);
        end

        % ------------------------------------------------------------
        % WLNM experiments
        % ------------------------------------------------------------
        if config.useParallel
            res_block = repmat(make_result_template(K, ratioTrain, rb, empty_split_stats(), config, 0, 0), config.numExperiments, 1);

            start_idx = 1;
            if save_confusion_flag
                res_block(1) = one_experiment_dir_neg( ...
                    1, base_seed, dataname, net, K, ratioTrain, rb, ...
                    use_backbone, bb_mask, config, taxonomy, mass, role, nodeSelection, ...
                    shared_train, shared_test, shared_split_stats, ...
                    true, export_backbone_flag, artifact_dir, threshold_mode, fixed_threshold, version, ...
                    encode_parallel, compute_ecological_metrics);
                start_idx = 2;
            end

            if start_idx <= config.numExperiments
                parfor i = start_idx:config.numExperiments
                    res_block(i) = one_experiment_dir_neg( ...
                        i, base_seed, dataname, net, K, ratioTrain, rb, ...
                        use_backbone, bb_mask, config, taxonomy, mass, role, nodeSelection, ...
                        shared_train, shared_test, shared_split_stats, ...
                        false, false, artifact_dir, threshold_mode, fixed_threshold, version, ...
                        encode_parallel, compute_ecological_metrics);
                end
            end

            for i = 1:config.numExperiments
                row = row + 1;
                results(row) = res_block(i);
            end

        else
            for i = 1:config.numExperiments
                do_export = save_confusion_flag && (i == 1);
                row = row + 1;
                results(row) = one_experiment_dir_neg( ...
                    i, base_seed, dataname, net, K, ratioTrain, rb, ...
                    use_backbone, bb_mask, config, taxonomy, mass, role, nodeSelection, ...
                    shared_train, shared_test, shared_split_stats, ...
                    do_export, export_backbone_flag, artifact_dir, threshold_mode, fixed_threshold, version, ...
                    encode_parallel, compute_ecological_metrics);
            end
        end
    end
end

function r = one_experiment_dir_neg(expID, base_seed, dataname, net, K, ratioTrain, rb, ...
        use_backbone, bb_mask, config, taxonomy, mass, role, nodeSelection, ...
        shared_train, shared_test, shared_split_stats, save_confusion, export_backbone_flag, ...
        artifact_dir, threshold_mode, fixed_threshold, version, encode_parallel, compute_ecological_metrics)

    seed = make_experiment_seed(base_seed, dataname, K, ratioTrain, rb, expID);
    rng(seed, 'twister');

    if isempty(shared_train)
        [train, test, split_stats] = get_split(net, ratioTrain, rb, use_backbone, bb_mask, config);
    else
        train = shared_train;
        test = shared_test;
        split_stats = shared_split_stats;
    end

    artifact_tag = make_artifact_tag(version, expID, seed, rb, config.inverse_backbone);

    t0 = tic;
    [roc_auc, pr_auc, thr, prec, rec, f1, aux] = WLNM_dir_neg( ...
        dataname, train, test, K, taxonomy, mass, role, nodeSelection, ratioTrain, ...
        'save_confusion', save_confusion, ...
        'backbone_mask', bb_mask, ...
        'export_backbone', (save_confusion && use_backbone && export_backbone_flag), ...
        'evaluate_on_all_unseen', config.evaluate_on_all_unseen, ...
        'artifact_tag', artifact_tag, ...
        'artifact_dir', artifact_dir, ...
        'threshold_mode', threshold_mode, ...
        'fixed_threshold', fixed_threshold, ...
        'encode_parallel', encode_parallel, ...
        'compute_ecological_metrics', compute_ecological_metrics);

    r = make_result_template(K, ratioTrain, rb, split_stats, config, expID, seed);
    r = populate_result_row(r, roc_auc, pr_auc, thr, prec, rec, f1, toc(t0), aux);
end

function [train, test, split_stats] = get_split(net, ratioTrain, rb, use_backbone, bb_mask, config)
    if use_backbone
        fprintf('[SweepBackbone] ratioTrain=%.2f | BackboneRatio=%.2f | inverse_backbone=%d\n', ...
            ratioTrain, rb, config.inverse_backbone);

        args = { ...
            'use_backbone',      true, ...
            'ratioBackbone',     rb, ...
            'inverse_backbone',  config.inverse_backbone, ...
            'backbone_mask',     bb_mask ...
        };

        [train, test, split_stats] = DivideNet_dir_neg( ...
            net, ratioTrain, config.checkConnectivity, config.adaptiveConnectivity, args{:});
    else
        [train, test, split_stats] = DivideNet_dir_neg( ...
            net, ratioTrain, config.checkConnectivity, config.adaptiveConnectivity);
    end
end

% ============================================================
% Result row template
% ============================================================
function out = make_result_template(K, ratioTrain, rb, split_stats, config, expID, seed)
    if nargin < 5 || isempty(config)
        config = struct();
    end
    if nargin < 6
        expID = 0;
    end
    if nargin < 7
        seed = 0;
    end

    out = struct( ...
        'Version',get_config_text(config, 'version', 'WLNM_dir_neg'), ...
        'ROC_AUC',0, 'PR_AUC',0, 'TimeElapsed','', ...
        'K',K, 'TrainRatio',ratioTrain, 'BackboneRatio',rb, ...
        'ExperimentID',expID, ...
        'Seed',seed, ...
        'ThresholdMode',get_config_text(config, 'thresholdMode', 'fixed'), ...
        'CvK',0, 'FoldID',0, 'NumFolds',0, ...
        'Threshold',0, 'Precision',0, 'Recall',0, 'F1Score',0, ...
        'TestTP',NaN, ...
        'TestFP',NaN, ...
        'TestFN',NaN, ...
        'TestTN',NaN, ...
        'TestTPR',NaN, ...
        'TestTNR',NaN, ...
        'TestFPR',NaN, ...
        'TestFNR',NaN, ...
        'TestPrecision',NaN, ...
        'TestRecall',NaN, ...
        'TestF1Score',NaN, ...
        'TestAccuracy',NaN, ...
        'TestExpectedAccuracy',NaN, ...
        'TestKappa',NaN, ...
        'TestMCC',NaN, ...
        'TestTSS',NaN, ...
        'TotalLinks',split_stats.TotalLinks, ...
        'TrainLinks',split_stats.TrainLinks, ...
        'TestLinks',split_stats.TestLinks, ...
        'BackboneTotal',split_stats.BackboneTotal, ...
        'NonBackboneTotal',split_stats.NonBackboneTotal, ...
        'BackboneTrainLinks',split_stats.BackboneTrainLinks, ...
        'NonBackboneTrainLinks',split_stats.NonBackboneTrainLinks, ...
        'BackboneTestLinks',split_stats.BackboneTestLinks, ...
        'NonBackboneTestLinks',split_stats.NonBackboneTestLinks, ...
        'EmpiricalNumSpecies',NaN, ...
        'EmpiricalLinks',NaN, ...
        'EmpiricalConnectance',NaN, ...
        'EmpiricalMeanTrophicLevel',NaN, ...
        'EmpiricalMeanDegree',NaN, ...
        'EmpiricalMeanGenerality',NaN, ...
        'EmpiricalMeanVulnerability',NaN, ...
        'EmpiricalPropBasal',NaN, ...
        'EmpiricalPropIntermediate',NaN, ...
        'EmpiricalPropTop',NaN, ...
        'PseudoNumSpecies',NaN, ...
        'PseudoLinks',NaN, ...
        'PseudoConnectance',NaN, ...
        'PseudoMeanTrophicLevel',NaN, ...
        'PseudoMeanDegree',NaN, ...
        'PseudoMeanGenerality',NaN, ...
        'PseudoMeanVulnerability',NaN, ...
        'PseudoPropBasal',NaN, ...
        'PseudoPropIntermediate',NaN, ...
        'PseudoPropTop',NaN, ...
        'DeltaLinks',NaN, ...
        'DeltaConnectance',NaN, ...
        'DeltaMeanTrophicLevel',NaN, ...
        'DeltaMeanDegree',NaN, ...
        'DeltaMeanGenerality',NaN, ...
        'DeltaMeanVulnerability',NaN, ...
        'DeltaPropBasal',NaN, ...
        'DeltaPropIntermediate',NaN, ...
        'DeltaPropTop',NaN, ...
        'TestTP',NaN, ...
        'TestFP',NaN, ...
        'TestFN',NaN, ...
        'TestTN',NaN, ...
        'TestTPR',NaN, ...
        'TestTNR',NaN, ...
        'TestFPR',NaN, ...
        'TestFNR',NaN, ...
        'TestPrecision',NaN, ...
        'TestRecall',NaN, ...
        'TestF1Score',NaN, ...
        'TestAccuracy',NaN, ...
        'TestExpectedAccuracy',NaN, ...
        'TestKappa',NaN, ...
        'TestMCC',NaN, ...
        'TestTSS',NaN, ...
        'PseudoTP',NaN, ...
        'PseudoFP',NaN, ...
        'PseudoFN',NaN, ...
        'PseudoTN',NaN, ...
        'PseudoTPR',NaN, ...
        'PseudoTNR',NaN, ...
        'PseudoFPR',NaN, ...
        'PseudoFNR',NaN, ...
        'PseudoPrecision',NaN, ...
        'PseudoRecall',NaN, ...
        'PseudoF1Score',NaN, ...
        'PseudoMCC',NaN, ...
        'PseudoTSS',NaN, ...
        'PseudoJaccardLinks',NaN, ...
        'NumPredictedNovelLinks',NaN, ...
        'NumTrueNovelLinks',NaN, ...
        'EvaluateOnAllUnseen',NaN ...
    );

    out = add_extended_metric_defaults(out, 'Empirical');
    out = add_extended_metric_defaults(out, 'Pseudo');
    out = add_extended_metric_defaults(out, 'Delta');
end

% ============================================================
% Empty split stats template
% ============================================================
function st = empty_split_stats()
    st = struct( ...
        'TotalLinks',0, ...
        'TrainLinks',0, ...
        'TestLinks',0, ...
        'BackboneTotal',0, ...
        'NonBackboneTotal',0, ...
        'BackboneTrainLinks',0, ...
        'NonBackboneTrainLinks',0, ...
        'BackboneTestLinks',0, ...
        'NonBackboneTestLinks',0 ...
    );
end

% ============================================================
% Fill predictive + ecological metrics into result row
% ============================================================
function out = populate_result_row(out, roc_auc, pr_auc, thr, prec, rec, f1, elapsed_seconds, aux)

    out.ROC_AUC     = roc_auc;
    out.PR_AUC      = pr_auc;
    out.TimeElapsed = datestr(seconds(elapsed_seconds), 'HH:MM:SS');
    out.Threshold   = thr;
    out.Precision   = prec;
    out.Recall      = rec;
    out.F1Score     = f1;

    flat = flatten_aux_metrics(aux);
    fn = fieldnames(flat);
    for k = 1:numel(fn)
        out.(fn{k}) = flat.(fn{k});
    end
end

% ============================================================
% Flatten aux struct from WLNM_dir_neg into scalar fields
% ============================================================
function flat = flatten_aux_metrics(aux)

    flat = struct( ...
        'EmpiricalNumSpecies',NaN, ...
        'EmpiricalLinks',NaN, ...
        'EmpiricalConnectance',NaN, ...
        'EmpiricalMeanTrophicLevel',NaN, ...
        'EmpiricalMeanDegree',NaN, ...
        'EmpiricalMeanGenerality',NaN, ...
        'EmpiricalMeanVulnerability',NaN, ...
        'EmpiricalPropBasal',NaN, ...
        'EmpiricalPropIntermediate',NaN, ...
        'EmpiricalPropTop',NaN, ...
        'PseudoNumSpecies',NaN, ...
        'PseudoLinks',NaN, ...
        'PseudoConnectance',NaN, ...
        'PseudoMeanTrophicLevel',NaN, ...
        'PseudoMeanDegree',NaN, ...
        'PseudoMeanGenerality',NaN, ...
        'PseudoMeanVulnerability',NaN, ...
        'PseudoPropBasal',NaN, ...
        'PseudoPropIntermediate',NaN, ...
        'PseudoPropTop',NaN, ...
        'DeltaLinks',NaN, ...
        'DeltaConnectance',NaN, ...
        'DeltaMeanTrophicLevel',NaN, ...
        'DeltaMeanDegree',NaN, ...
        'DeltaMeanGenerality',NaN, ...
        'DeltaMeanVulnerability',NaN, ...
        'DeltaPropBasal',NaN, ...
        'DeltaPropIntermediate',NaN, ...
        'DeltaPropTop',NaN, ...
        'PseudoTP',NaN, ...
        'PseudoFP',NaN, ...
        'PseudoFN',NaN, ...
        'PseudoTN',NaN, ...
        'PseudoTPR',NaN, ...
        'PseudoTNR',NaN, ...
        'PseudoFPR',NaN, ...
        'PseudoFNR',NaN, ...
        'PseudoPrecision',NaN, ...
        'PseudoRecall',NaN, ...
        'PseudoF1Score',NaN, ...
        'PseudoMCC',NaN, ...
        'PseudoTSS',NaN, ...
        'PseudoJaccardLinks',NaN, ...
        'NumPredictedNovelLinks',NaN, ...
        'NumTrueNovelLinks',NaN, ...
        'EvaluateOnAllUnseen',NaN ...
    );

    flat = add_extended_metric_defaults(flat, 'Empirical');
    flat = add_extended_metric_defaults(flat, 'Pseudo');
    flat = add_extended_metric_defaults(flat, 'Delta');

    if nargin == 0 || isempty(aux)
        return;
    end

    % ---- empirical metrics ----
    if isfield(aux, 'empirical_metrics') && ~isempty(aux.empirical_metrics)
        m = aux.empirical_metrics;
        flat.EmpiricalNumSpecies        = safe_field(m, 'NumSpecies');
        flat.EmpiricalLinks             = safe_field(m, 'NumLinks');
        flat.EmpiricalConnectance       = safe_field(m, 'Connectance');
        flat.EmpiricalMeanTrophicLevel  = safe_field(m, 'MeanTrophicLevel');
        flat.EmpiricalMeanDegree        = safe_field(m, 'MeanDegree');
        flat.EmpiricalMeanGenerality    = safe_field(m, 'MeanGenerality');
        flat.EmpiricalMeanVulnerability = safe_field(m, 'MeanVulnerability');
        flat.EmpiricalPropBasal         = safe_field(m, 'PropBasal');
        flat.EmpiricalPropIntermediate  = safe_field(m, 'PropIntermediate');
        flat.EmpiricalPropTop           = safe_field(m, 'PropTop');
        flat = copy_extended_metrics(flat, m, 'Empirical');
    end

    % ---- pseudo metrics ----
    if isfield(aux, 'pseudo_metrics') && ~isempty(aux.pseudo_metrics)
        m = aux.pseudo_metrics;
        flat.PseudoNumSpecies        = safe_field(m, 'NumSpecies');
        flat.PseudoLinks             = safe_field(m, 'NumLinks');
        flat.PseudoConnectance       = safe_field(m, 'Connectance');
        flat.PseudoMeanTrophicLevel  = safe_field(m, 'MeanTrophicLevel');
        flat.PseudoMeanDegree        = safe_field(m, 'MeanDegree');
        flat.PseudoMeanGenerality    = safe_field(m, 'MeanGenerality');
        flat.PseudoMeanVulnerability = safe_field(m, 'MeanVulnerability');
        flat.PseudoPropBasal         = safe_field(m, 'PropBasal');
        flat.PseudoPropIntermediate  = safe_field(m, 'PropIntermediate');
        flat.PseudoPropTop           = safe_field(m, 'PropTop');
        flat = copy_extended_metrics(flat, m, 'Pseudo');
    end

    % ---- deltas ----
    flat.DeltaLinks             = flat.PseudoLinks            - flat.EmpiricalLinks;
    flat.DeltaConnectance       = flat.PseudoConnectance      - flat.EmpiricalConnectance;
    flat.DeltaMeanTrophicLevel  = flat.PseudoMeanTrophicLevel - flat.EmpiricalMeanTrophicLevel;
    flat.DeltaMeanDegree        = flat.PseudoMeanDegree       - flat.EmpiricalMeanDegree;
    flat.DeltaMeanGenerality    = flat.PseudoMeanGenerality   - flat.EmpiricalMeanGenerality;
    flat.DeltaMeanVulnerability = flat.PseudoMeanVulnerability- flat.EmpiricalMeanVulnerability;
    flat.DeltaPropBasal         = flat.PseudoPropBasal        - flat.EmpiricalPropBasal;
    flat.DeltaPropIntermediate  = flat.PseudoPropIntermediate - flat.EmpiricalPropIntermediate;
    flat.DeltaPropTop           = flat.PseudoPropTop          - flat.EmpiricalPropTop;
    flat = compute_extended_metric_deltas(flat);

    % ---- test-set classification metrics ----
    if isfield(aux, 'test_metrics') && ~isempty(aux.test_metrics)
        t = aux.test_metrics;
        flat.TestTP        = safe_field(t, 'TP');
        flat.TestFP        = safe_field(t, 'FP');
        flat.TestFN        = safe_field(t, 'FN');
        flat.TestTN        = safe_field(t, 'TN');
        flat.TestTPR       = safe_field(t, 'TPR');
        flat.TestTNR       = safe_field(t, 'TNR');
        flat.TestFPR       = safe_field(t, 'FPR');
        flat.TestFNR       = safe_field(t, 'FNR');
        flat.TestPrecision = safe_field(t, 'Precision');
        flat.TestRecall    = safe_field(t, 'Recall');
        flat.TestF1Score   = safe_field(t, 'F1Score');
        flat.TestAccuracy  = safe_field(t, 'Accuracy');
        flat.TestExpectedAccuracy = safe_field(t, 'ExpectedAccuracy');
        flat.TestKappa     = safe_field(t, 'Kappa');
        flat.TestMCC       = safe_field(t, 'MCC');
        flat.TestTSS       = safe_field(t, 'TSS');
    end

    % ---- comparison metrics ----
    if isfield(aux, 'comparison_metrics') && ~isempty(aux.comparison_metrics)
        c = aux.comparison_metrics;
        flat.PseudoTP           = safe_field(c, 'TP');
        flat.PseudoFP           = safe_field(c, 'FP');
        flat.PseudoFN           = safe_field(c, 'FN');
        flat.PseudoTN           = safe_field(c, 'TN');
        flat.PseudoTPR          = safe_field(c, 'TPR');
        flat.PseudoTNR          = safe_field(c, 'TNR');
        flat.PseudoFPR          = safe_field(c, 'FPR');
        flat.PseudoFNR          = safe_field(c, 'FNR');
        flat.PseudoPrecision    = safe_field(c, 'Precision');
        flat.PseudoRecall       = safe_field(c, 'Recall');
        flat.PseudoF1Score      = safe_field(c, 'F1Score');
        flat.PseudoMCC          = safe_field(c, 'MCC');
        flat.PseudoTSS          = safe_field(c, 'TSS');
        flat.PseudoJaccardLinks = safe_field(c, 'JaccardLinks');
    end

    % ---- bookkeeping ----
    if isfield(aux, 'NumPredictedNovelLinks')
        flat.NumPredictedNovelLinks = aux.NumPredictedNovelLinks;
    end
    if isfield(aux, 'NumTrueNovelLinks')
        flat.NumTrueNovelLinks = aux.NumTrueNovelLinks;
    end
    if isfield(aux, 'EvaluateOnAllUnseen')
        flat.EvaluateOnAllUnseen = double(aux.EvaluateOnAllUnseen);
    end
end

% ============================================================
% Safe struct field access
% ============================================================
function s = add_extended_metric_defaults(s, prefix)
    suffixes = extended_metric_suffixes();
    for i = 1:numel(suffixes)
        s.([prefix suffixes{i}]) = NaN;
    end
end

function s = copy_extended_metrics(s, metrics, prefix)
    suffixes = extended_metric_suffixes();
    for i = 1:numel(suffixes)
        suffix = suffixes{i};
        s.([prefix suffix]) = safe_field(metrics, suffix);
    end
end

function s = compute_extended_metric_deltas(s)
    suffixes = extended_metric_suffixes();
    for i = 1:numel(suffixes)
        suffix = suffixes{i};
        s.(['Delta' suffix]) = s.(['Pseudo' suffix]) - s.(['Empirical' suffix]);
    end
end

function suffixes = extended_metric_suffixes()
    suffixes = { ...
        'DegreeStd', ...
        'DegreeCV', ...
        'DegreeGini', ...
        'GeneralityStd', ...
        'GeneralityCV', ...
        'GeneralityGini', ...
        'VulnerabilityStd', ...
        'VulnerabilityCV', ...
        'VulnerabilityGini', ...
        'TrophicLevelStd', ...
        'TrophicLevelCV', ...
        'TrophicLevelRange', ...
        'MeanLocalClustering', ...
        'Transitivity', ...
        'NumTriangles', ...
        'TriangleDensity', ...
        'MeanDietOverlap' ...
    };
end

function val = safe_field(s, f)
    if isstruct(s) && isfield(s, f) && ~isempty(s.(f))
        val = s.(f);
    else
        val = NaN;
    end
end

function seed = make_experiment_seed(base_seed, dataname, K, ratioTrain, rb, expID)
    name_hash = sum(double(char(string(dataname))));
    raw = double(base_seed) ...
        + 1000003 * name_hash ...
        + 1009 * double(K) ...
        + 9173 * round(1000 * double(ratioTrain)) ...
        + 131 * round(1000 * double(rb)) ...
        + double(expID);
    seed = mod(round(raw), 2147483646) + 1;
end

function tag = make_artifact_tag(version, expID, seed, rb, inverse_backbone)
    if inverse_backbone
        rb_tag = sprintf('nonbb%03d', round(100 * rb));
    else
        rb_tag = sprintf('bb%03d', round(100 * rb));
    end
    tag = sprintf('%s_%s_exp%03d_seed%d', lower(char(string(version))), rb_tag, expID, seed);
end

function value = get_config_bool(config, field, default_value)
    if isfield(config, field) && ~isempty(config.(field))
        value = logical(config.(field));
    else
        value = logical(default_value);
    end
end

function value = get_config_number(config, field, default_value)
    if isfield(config, field) && ~isempty(config.(field))
        value = config.(field);
    else
        value = default_value;
    end
end

function value = get_config_text(config, field, default_value)
    if isfield(config, field) && ~isempty(config.(field))
        value = char(string(config.(field)));
    else
        value = char(string(default_value));
    end
end
