function margins = default_delta_equivalence_margins()
%DEFAULT_DELTA_EQUIVALENCE_MARGINS Default practical equivalence margins.
%
% Margins are expressed on the same raw scale as:
%
%   Delta = pseudo_metric - empirical_metric
%
% Count metrics that scale directly with network size, such as Links and
% NumTriangles, are intentionally omitted. Those should be tested only after
% defining a size-normalized margin.

    metric = { ...
        'Connectance'; ...
        'MeanTrophicLevel'; ...
        'MeanDegree'; ...
        'MeanGenerality'; ...
        'MeanVulnerability'; ...
        'PropBasal'; ...
        'PropIntermediate'; ...
        'PropTop'; ...
        'DegreeStd'; ...
        'DegreeCV'; ...
        'DegreeGini'; ...
        'GeneralityStd'; ...
        'GeneralityCV'; ...
        'GeneralityGini'; ...
        'VulnerabilityStd'; ...
        'VulnerabilityCV'; ...
        'VulnerabilityGini'; ...
        'TrophicLevelStd'; ...
        'TrophicLevelCV'; ...
        'TrophicLevelRange'; ...
        'MeanLocalClustering'; ...
        'Transitivity'; ...
        'TriangleDensity'; ...
        'MeanDietOverlap' ...
    };

    upper = [ ...
        0.01; ...  % Connectance: one percentage point on a 0-1 scale.
        0.10; ...  % Mean trophic level: one tenth of a trophic level.
        0.50; ...  % Mean degree: half an interaction per species on average.
        0.50; ...  % Mean generality: half a prey item per consumer on average.
        0.50; ...  % Mean vulnerability: half a consumer per resource on average.
        0.05; ...  % Role proportions: five percentage points.
        0.05; ...
        0.05; ...
        0.50; ...  % Degree dispersion on interaction-count scale.
        0.10; ...  % Coefficients of variation: ten percentage points.
        0.05; ...  % Gini coefficients: five percentage points.
        0.50; ...
        0.10; ...
        0.05; ...
        0.50; ...
        0.10; ...
        0.05; ...
        0.10; ...
        0.10; ...
        0.25; ...  % Trophic-level range: quarter trophic level.
        0.05; ...  % Bounded closure/overlap metrics: five percentage points.
        0.05; ...
        0.05; ...
        0.05 ...
    ];

    lower = -upper;

    mode = repmat({'absolute'}, numel(metric), 1);
    justification = { ...
        'One percentage point on a 0-1 connectance scale is small enough to be practically negligible.'; ...
        'A tenth of a trophic level is below a coarse ecological interpretation threshold.'; ...
        'Half an interaction per species on average is a small structural deviation.'; ...
        'Half a prey item per consumer on average is a small diet-breadth deviation.'; ...
        'Half a consumer per resource on average is a small vulnerability deviation.'; ...
        'Five percentage points is a small change in species-role composition.'; ...
        'Five percentage points is a small change in species-role composition.'; ...
        'Five percentage points is a small change in species-role composition.'; ...
        'Half an interaction on the degree-dispersion scale is a small structural deviation.'; ...
        'Ten percentage points is a small relative-dispersion deviation.'; ...
        'Five percentage points is a small inequality deviation on a bounded 0-1 scale.'; ...
        'Half an interaction on the generality-dispersion scale is a small structural deviation.'; ...
        'Ten percentage points is a small relative-dispersion deviation.'; ...
        'Five percentage points is a small inequality deviation on a bounded 0-1 scale.'; ...
        'Half an interaction on the vulnerability-dispersion scale is a small structural deviation.'; ...
        'Ten percentage points is a small relative-dispersion deviation.'; ...
        'Five percentage points is a small inequality deviation on a bounded 0-1 scale.'; ...
        'A tenth of a trophic level is a small trophic-dispersion deviation.'; ...
        'Ten percentage points is a small relative-dispersion deviation.'; ...
        'A quarter trophic level is a small range deviation.'; ...
        'Five percentage points is a small deviation on a bounded 0-1 closure metric.'; ...
        'Five percentage points is a small deviation on a bounded 0-1 closure metric.'; ...
        'Five percentage points is a small deviation on a bounded 0-1 closure metric.'; ...
        'Five percentage points is a small deviation on a bounded 0-1 diet-overlap metric.' ...
    };

    margins = table(metric, lower, upper, mode, justification, ...
        'VariableNames', { ...
            'Metric', ...
            'LowerMargin', ...
            'UpperMargin', ...
            'MarginMode', ...
            'Justification' ...
        });
end
