function summary = write_delta_ttest_summary(summary_file, results, varargin)
%WRITE_DELTA_TTEST_SUMMARY Write paired-difference t-tests for food-web metrics.
%
% This implements empirical-vs-generated food-web comparison as a one-sample
% t-test on paired differences:
%
%   delta = pseudo_metric - empirical_metric
%
% Repeated runs for the same food web are averaged first. The t-test is then
% performed across food-web-level mean deltas, avoiding pseudoreplication
% from repeated train/test splits or neural-network fits.
%
% Student's t p-values are computed with betainc, so this file does not
% require MATLAB's Statistics and Machine Learning Toolbox.

    p = inputParser;
    addParameter(p, 'alpha', 0.05);
    addParameter(p, 'version', '');
    addParameter(p, 'byEcosystemFile', '');
    parse(p, varargin{:});
    opt = p.Results;

    if nargin < 1 || isempty(summary_file)
        error('write_delta_ttest_summary:MissingFile', ...
            'summary_file must be provided.');
    end

    if nargin < 2 || isempty(results)
        summary = empty_summary_table();
        write_summary_table(summary_file, summary);
        by_ecosystem_file = char(string(opt.byEcosystemFile));
        if ~isempty(by_ecosystem_file)
            ecosystem_summary = empty_ecosystem_summary_table();
            write_summary_table(by_ecosystem_file, ecosystem_summary);
        end
        return;
    end

    alpha = double(opt.alpha);
    version = char(string(opt.version));
    by_ecosystem_file = char(string(opt.byEcosystemFile));

    structural_metric_names = extended_structural_metric_names();

    metric_names = [ ...
    { ...
        'Links', ...
        'Connectance', ...
        'MeanTrophicLevel', ...
        'MeanDegree', ...
        'MeanGenerality', ...
        'MeanVulnerability', ...
        'PropBasal', ...
        'PropIntermediate', ...
        'PropTop' ...
    }, ...
    structural_metric_names];

    metric_fields = strcat('Delta', metric_names);
    empirical_fields = strcat('Empirical', metric_names);
    pseudo_fields = strcat('Pseudo', metric_names);

    groups = build_groups(results);

    out = struct( ...
        'Version', {{}}, ...
        'TestType', {{}}, ...
        'Metric', {{}}, ...
        'K', [], ...
        'TrainRatio', [], ...
        'BackboneRatio', [], ...
        'CvK', [], ...
        'ThresholdMode', {{}}, ...
        'EvaluateOnAllUnseen', [], ...
        'NumFoodWebs', [], ...
        'NumResultRows', [], ...
        'MeanDelta', [], ...
        'StdDelta', [], ...
        'TStatistic', [], ...
        'DF', [], ...
        'PValue', [], ...
        'Alpha', [], ...
        'RejectH0', [] ...
    );

    test_type = 'one_sample_ttest_on_foodweb_mean_paired_deltas';

    for g = 1:numel(groups)
        idx = groups(g).Indices;

        for m = 1:numel(metric_fields)
            field = metric_fields{m};
            foodweb_means = foodweb_level_means(results(idx), field);
            [t_stat, df, p_value, mean_delta, sd_delta, n_foodwebs] = ...
                one_sample_ttest_against_zero(foodweb_means);

            out.Version{end+1, 1} = version; %#ok<AGROW>
            out.TestType{end+1, 1} = test_type; %#ok<AGROW>
            out.Metric{end+1, 1} = metric_names{m}; %#ok<AGROW>
            out.K(end+1, 1) = groups(g).K; %#ok<AGROW>
            out.TrainRatio(end+1, 1) = groups(g).TrainRatio; %#ok<AGROW>
            out.BackboneRatio(end+1, 1) = groups(g).BackboneRatio; %#ok<AGROW>
            out.CvK(end+1, 1) = groups(g).CvK; %#ok<AGROW>
            out.ThresholdMode{end+1, 1} = groups(g).ThresholdMode; %#ok<AGROW>
            out.EvaluateOnAllUnseen(end+1, 1) = groups(g).EvaluateOnAllUnseen; %#ok<AGROW>
            out.NumFoodWebs(end+1, 1) = n_foodwebs; %#ok<AGROW>
            out.NumResultRows(end+1, 1) = numel(idx); %#ok<AGROW>
            out.MeanDelta(end+1, 1) = mean_delta; %#ok<AGROW>
            out.StdDelta(end+1, 1) = sd_delta; %#ok<AGROW>
            out.TStatistic(end+1, 1) = t_stat; %#ok<AGROW>
            out.DF(end+1, 1) = df; %#ok<AGROW>
            out.PValue(end+1, 1) = p_value; %#ok<AGROW>
            out.Alpha(end+1, 1) = alpha; %#ok<AGROW>
            out.RejectH0(end+1, 1) = double(isfinite(p_value) && p_value < alpha); %#ok<AGROW>
        end
    end

    summary = table( ...
        out.Version, ...
        out.TestType, ...
        out.Metric, ...
        out.K, ...
        out.TrainRatio, ...
        out.BackboneRatio, ...
        out.CvK, ...
        out.ThresholdMode, ...
        out.EvaluateOnAllUnseen, ...
        out.NumFoodWebs, ...
        out.NumResultRows, ...
        out.MeanDelta, ...
        out.StdDelta, ...
        out.TStatistic, ...
        out.DF, ...
        out.PValue, ...
        out.Alpha, ...
        out.RejectH0, ...
        'VariableNames', { ...
            'Version', ...
            'TestType', ...
            'Metric', ...
            'K', ...
            'TrainRatio', ...
            'BackboneRatio', ...
            'CvK', ...
            'ThresholdMode', ...
            'EvaluateOnAllUnseen', ...
            'NumFoodWebs', ...
            'NumResultRows', ...
            'MeanDelta', ...
            'StdDelta', ...
            'TStatistic', ...
            'DF', ...
            'PValue', ...
            'Alpha', ...
            'RejectH0' ...
        });
    write_summary_table(summary_file, summary);

    fprintf('[DeltaTTest] Wrote %d rows to %s\n', height(summary), summary_file);

    if ~isempty(by_ecosystem_file)
        ecosystem_summary = build_ecosystem_summary( ...
            results, metric_fields, empirical_fields, pseudo_fields, ...
            metric_names, alpha, version);
        write_summary_table(by_ecosystem_file, ecosystem_summary);

        fprintf('[DeltaTTest] Wrote %d ecosystem rows to %s\n', ...
            height(ecosystem_summary), by_ecosystem_file);
    end
end

function summary = build_ecosystem_summary( ...
    results, metric_fields, empirical_fields, pseudo_fields, ...
    metric_names, alpha, version)

    groups = build_groups(results, true);

    out = struct( ...
        'Version', {{}}, ...
        'TestType', {{}}, ...
        'Metric', {{}}, ...
        'EcosystemType', {{}}, ...
        'K', [], ...
        'TrainRatio', [], ...
        'BackboneRatio', [], ...
        'CvK', [], ...
        'ThresholdMode', {{}}, ...
        'EvaluateOnAllUnseen', [], ...
        'NumFoodWebs', [], ...
        'NumResultRows', [], ...
        'MeanEmpirical', [], ...
        'MeanPseudo', [], ...
        'MeanDelta', [], ...
        'StdDelta', [], ...
        'TStatistic', [], ...
        'DF', [], ...
        'PValue', [], ...
        'Alpha', [], ...
        'RejectH0', [] ...
    );

    test_type = 'one_sample_ttest_on_foodweb_mean_paired_deltas_by_ecosystem';

    for g = 1:numel(groups)
        idx = groups(g).Indices;
        group_rows = results(idx);

        for m = 1:numel(metric_fields)
            delta_means = foodweb_level_means(group_rows, metric_fields{m});
            empirical_means = foodweb_level_means(group_rows, empirical_fields{m});
            pseudo_means = foodweb_level_means(group_rows, pseudo_fields{m});

            [t_stat, df, p_value, mean_delta, sd_delta, n_foodwebs] = ...
                one_sample_ttest_against_zero(delta_means);
            if n_foodwebs == 0
                continue;
            end

            out.Version{end+1, 1} = version; %#ok<AGROW>
            out.TestType{end+1, 1} = test_type; %#ok<AGROW>
            out.Metric{end+1, 1} = metric_names{m}; %#ok<AGROW>
            out.EcosystemType{end+1, 1} = groups(g).EcosystemType; %#ok<AGROW>
            out.K(end+1, 1) = groups(g).K; %#ok<AGROW>
            out.TrainRatio(end+1, 1) = groups(g).TrainRatio; %#ok<AGROW>
            out.BackboneRatio(end+1, 1) = groups(g).BackboneRatio; %#ok<AGROW>
            out.CvK(end+1, 1) = groups(g).CvK; %#ok<AGROW>
            out.ThresholdMode{end+1, 1} = groups(g).ThresholdMode; %#ok<AGROW>
            out.EvaluateOnAllUnseen(end+1, 1) = groups(g).EvaluateOnAllUnseen; %#ok<AGROW>
            out.NumFoodWebs(end+1, 1) = n_foodwebs; %#ok<AGROW>
            out.NumResultRows(end+1, 1) = numel(idx); %#ok<AGROW>
            out.MeanEmpirical(end+1, 1) = mean_or_nan(empirical_means); %#ok<AGROW>
            out.MeanPseudo(end+1, 1) = mean_or_nan(pseudo_means); %#ok<AGROW>
            out.MeanDelta(end+1, 1) = mean_delta; %#ok<AGROW>
            out.StdDelta(end+1, 1) = sd_delta; %#ok<AGROW>
            out.TStatistic(end+1, 1) = t_stat; %#ok<AGROW>
            out.DF(end+1, 1) = df; %#ok<AGROW>
            out.PValue(end+1, 1) = p_value; %#ok<AGROW>
            out.Alpha(end+1, 1) = alpha; %#ok<AGROW>
            out.RejectH0(end+1, 1) = double(isfinite(p_value) && p_value < alpha); %#ok<AGROW>
        end
    end

    summary = table( ...
        out.Version, ...
        out.TestType, ...
        out.Metric, ...
        out.EcosystemType, ...
        out.K, ...
        out.TrainRatio, ...
        out.BackboneRatio, ...
        out.CvK, ...
        out.ThresholdMode, ...
        out.EvaluateOnAllUnseen, ...
        out.NumFoodWebs, ...
        out.NumResultRows, ...
        out.MeanEmpirical, ...
        out.MeanPseudo, ...
        out.MeanDelta, ...
        out.StdDelta, ...
        out.TStatistic, ...
        out.DF, ...
        out.PValue, ...
        out.Alpha, ...
        out.RejectH0, ...
        'VariableNames', { ...
            'Version', ...
            'TestType', ...
            'Metric', ...
            'EcosystemType', ...
            'K', ...
            'TrainRatio', ...
            'BackboneRatio', ...
            'CvK', ...
            'ThresholdMode', ...
            'EvaluateOnAllUnseen', ...
            'NumFoodWebs', ...
            'NumResultRows', ...
            'MeanEmpirical', ...
            'MeanPseudo', ...
            'MeanDelta', ...
            'StdDelta', ...
            'TStatistic', ...
            'DF', ...
            'PValue', ...
            'Alpha', ...
            'RejectH0' ...
        });
end

function groups = build_groups(results, include_ecosystem)
    if nargin < 2
        include_ecosystem = false;
    end

    groups = struct( ...
        'Key', {}, ...
        'Indices', {}, ...
        'EcosystemType', {}, ...
        'K', {}, ...
        'TrainRatio', {}, ...
        'BackboneRatio', {}, ...
        'CvK', {}, ...
        'ThresholdMode', {}, ...
        'EvaluateOnAllUnseen', {} ...
    );

    for i = 1:numel(results)
        k = scalar_field(results(i), 'K', NaN);
        train_ratio = scalar_field(results(i), 'TrainRatio', NaN);
        backbone_ratio = scalar_field(results(i), 'BackboneRatio', NaN);
        cv_k = scalar_field(results(i), 'CvK', 0);
        threshold_mode = text_field(results(i), 'ThresholdMode', '');
        evaluate_all = scalar_field(results(i), 'EvaluateOnAllUnseen', NaN);
        ecosystem_type = '';
        if include_ecosystem
            ecosystem_type = normalize_ecosystem_type( ...
                text_field(results(i), 'EcosystemType', 'Unknown'));
        end

        key = sprintf('K=%g|Train=%.12g|Backbone=%.12g|CvK=%g|Threshold=%s|EvalAll=%g', ...
            k, train_ratio, backbone_ratio, cv_k, threshold_mode, evaluate_all);
        if include_ecosystem
            key = sprintf('%s|Ecosystem=%s', key, ecosystem_type);
        end

        group_idx = find(strcmp({groups.Key}, key), 1, 'first');

        if isempty(group_idx)
            group_idx = numel(groups) + 1;
            groups(group_idx).Key = key;
            groups(group_idx).Indices = i;
            groups(group_idx).EcosystemType = ecosystem_type;
            groups(group_idx).K = k;
            groups(group_idx).TrainRatio = train_ratio;
            groups(group_idx).BackboneRatio = backbone_ratio;
            groups(group_idx).CvK = cv_k;
            groups(group_idx).ThresholdMode = threshold_mode;
            groups(group_idx).EvaluateOnAllUnseen = evaluate_all;
        else
            groups(group_idx).Indices(end+1) = i;
        end
    end
end

function value = mean_or_nan(x)
    x = x(:);
    x = x(isfinite(x));
    if isempty(x)
        value = NaN;
    else
        value = mean(x);
    end
end

function value = normalize_ecosystem_type(raw_value)
    value = char(strtrim(string(raw_value)));
    if isempty(value) || strcmpi(value, 'nan') || ...
            strcmpi(value, 'missing') || strcmpi(value, '<missing>')
        value = 'Unknown';
    end
end

function means = foodweb_level_means(rows, field)
    if isempty(rows)
        means = [];
        return;
    end

    foodwebs = cell(numel(rows), 1);
    for i = 1:numel(rows)
        foodwebs{i} = text_field(rows(i), 'Foodweb', sprintf('row_%d', i));
    end

    unique_foodwebs = unique(foodwebs, 'stable');
    means = NaN(numel(unique_foodwebs), 1);

    for f = 1:numel(unique_foodwebs)
        vals = [];
        for i = 1:numel(rows)
            if strcmp(foodwebs{i}, unique_foodwebs{f})
                vals(end+1, 1) = scalar_field(rows(i), field, NaN); %#ok<AGROW>
            end
        end

        vals = vals(isfinite(vals));
        if ~isempty(vals)
            means(f) = mean(vals);
        end
    end

    means = means(isfinite(means));
end

function [t_stat, df, p_value, mean_delta, sd_delta, n] = one_sample_ttest_against_zero(x)
    x = x(:);
    x = x(isfinite(x));

    n = numel(x);
    df = n - 1;

    if n == 0
        mean_delta = NaN;
        sd_delta = NaN;
        t_stat = NaN;
        p_value = NaN;
        return;
    end

    mean_delta = mean(x);

    if n == 1
        sd_delta = NaN;
        t_stat = NaN;
        p_value = NaN;
        return;
    end

    sd_delta = std(x, 0);

    if sd_delta == 0
        if mean_delta == 0
            t_stat = 0;
            p_value = 1;
        else
            t_stat = sign(mean_delta) * Inf;
            p_value = 0;
        end
        return;
    end

    t_stat = mean_delta / (sd_delta / sqrt(n));
    p_value = student_t_two_tailed_p(t_stat, df);
end

function p_value = student_t_two_tailed_p(t_stat, df)
    if ~isfinite(df) || df <= 0 || isnan(t_stat)
        p_value = NaN;
        return;
    end

    if isinf(t_stat)
        p_value = 0;
        return;
    end

    x = df / (df + t_stat.^2);
    ib = betainc(x, df / 2, 0.5);

    if t_stat >= 0
        cdf_value = 1 - 0.5 * ib;
    else
        cdf_value = 0.5 * ib;
    end

    p_value = 2 * min(cdf_value, 1 - cdf_value);
    p_value = max(0, min(1, p_value));
end

function value = scalar_field(s, field, default_value)
    if isstruct(s) && isfield(s, field) && ~isempty(s.(field)) && isscalar(s.(field))
        value = double(s.(field));
    else
        value = default_value;
    end
end

function value = text_field(s, field, default_value)
    if isstruct(s) && isfield(s, field) && ~isempty(s.(field))
        value = char(string(s.(field)));
    else
        value = char(string(default_value));
    end
end

function summary = empty_summary_table()
    summary = table( ...
        cell(0,1), cell(0,1), cell(0,1), ...
        zeros(0,1), zeros(0,1), zeros(0,1), zeros(0,1), ...
        cell(0,1), zeros(0,1), zeros(0,1), zeros(0,1), ...
        zeros(0,1), zeros(0,1), zeros(0,1), zeros(0,1), ...
        zeros(0,1), zeros(0,1), zeros(0,1), ...
        'VariableNames', { ...
            'Version', 'TestType', 'Metric', ...
            'K', 'TrainRatio', 'BackboneRatio', 'CvK', ...
            'ThresholdMode', 'EvaluateOnAllUnseen', 'NumFoodWebs', 'NumResultRows', ...
            'MeanDelta', 'StdDelta', 'TStatistic', 'DF', ...
            'PValue', 'Alpha', 'RejectH0' ...
        });
end

function summary = empty_ecosystem_summary_table()
    summary = table( ...
        cell(0,1), cell(0,1), cell(0,1), cell(0,1), ...
        zeros(0,1), zeros(0,1), zeros(0,1), zeros(0,1), ...
        cell(0,1), zeros(0,1), zeros(0,1), zeros(0,1), ...
        zeros(0,1), zeros(0,1), zeros(0,1), zeros(0,1), ...
        zeros(0,1), zeros(0,1), zeros(0,1), zeros(0,1), zeros(0,1), ...
        'VariableNames', { ...
            'Version', 'TestType', 'Metric', 'EcosystemType', ...
            'K', 'TrainRatio', 'BackboneRatio', 'CvK', ...
            'ThresholdMode', 'EvaluateOnAllUnseen', 'NumFoodWebs', 'NumResultRows', ...
            'MeanEmpirical', 'MeanPseudo', 'MeanDelta', 'StdDelta', ...
            'TStatistic', 'DF', 'PValue', 'Alpha', 'RejectH0' ...
        });
end

function names = extended_structural_metric_names()
    names = { ...
        'DegreeStd', ...
        'DegreeCV', ...
        'DegreeGini', ...
        'GeneralityStd', ...
        'GeneralityCV', ...
        'GeneralityGini', ...
        'VulnerabilityStd', ...
        'VulnerabilityCV', ...
        'VulnerabilityGini', ...
        'TrophicLevelStd', ...
        'TrophicLevelCV', ...
        'TrophicLevelRange', ...
        'NetworkXMeanTrophicLevel', ...
        'MeanLocalClustering', ...
        'Transitivity', ...
        'NumTriangles', ...
        'TriangleDensity', ...
        'MeanDietOverlap' ...
    };
end

function write_summary_table(summary_file, summary)
    out_dir = fileparts(summary_file);
    if ~isempty(out_dir) && ~exist(out_dir, 'dir')
        mkdir(out_dir);
    end

    writetable(summary, summary_file);
end
